### ISSUE TITLE
Message on top of "Admin Menus" beta

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#100]
> "Note: In some cases, blocking menu page access may leave related permissions. Review third party plugin documentation and adjust Subscriber Capabilities as needed."

I'm not sure if this helpful to users. I wonder how we can make this clearer or more actionable?

**Comment by agapetry** [comment]
@stevejburge We would like for an Admin menu restriction to block all related third party plugin operations, but that is not always the case. There needs to some disclaimer on this screen to avoid misunderstandings.

**Comment by stevejburge** [comment]
@agapetry Thanks. What kind of exceptions are we looking out for?

**Comment by agapetry** [comment]
@stevejburge What do you think of this? 

Note: When blocking plugin access, also review Subscriber Capabilities per third party documentation.

**Comment by agapetry** [comment]
"Note: You are only restricting access to admin menu screens. Some plugins may also add features to other areas of WordPress."

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/f515b037d1c6ea2c298e46ffe9813fee65a3ccfe
