### ISSUE TITLE
"Nav Menus" beta not working

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#101]
I'm testing a relatively simple setup. One menu with one page, and four posts:
<img width="339" alt="Screen Shot 2021-01-28 at 1 43 18 PM" src="https://user-images.githubusercontent.com/3868028/106183943-e5861a80-616e-11eb-896f-6843e6c22a1d.png">

The restrictions aren't working for me on an "Author" account. I can repeat the problem with a "Logged Out Users" option and with other types of menu links
<img width="352" alt="Screen Shot 2021-01-28 at 1 45 26 PM" src="https://user-images.githubusercontent.com/3868028/106184133-241bd500-616f-11eb-8069-04e796a6d14f.png">

**Comment by olatechpro** [comment]
Hi @agapetry, can you confirm if this is an error from my end or maybe the restriction code hasn't been migrated?

**Comment by agapetry** [comment]
@olatechpro Pro was missing one line of code to load your 'wp_get_nav_menu_items' filter.
