### ISSUE TITLE
Double-check the plugin safeguards

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#1031]
Can we double-check the plugin safeguards and make sure a user in the Administrator role can never lock themselves out of the plugin, no matter how badly they try?

https://secure.helpscout.net/conversation/2423671907/213150?folderId=2557458

**Comment by olatechpro** [comment]
Not from the plugin but most reports we've had related to this topic is from external plugin or direct database edit.

If there's a use case where it happen, it needed to be discuss so it can be check. @stevejburge

**Comment by stevejburge** [comment]
OK, fair point. Thanks, Ola
