### ISSUE TITLE
Can the Extractor check for Roles too?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#1032]
Our Extractor can check for Capabilities. I wonder if we can also link specific roles to a plugin? For example, we show "WooCommerce" or "Yoast SEO" in the "Role Type" column:

![Screenshot 2023-11-16 at 2 00 46 PM](https://github.com/publishpress/PublishPress-Capabilities/assets/3868028/dc6d1534-439e-4614-80b0-80688431595e)

**Comment by olatechpro** [comment]
@stevejburge We currently don't have this feature and it should be a feature needed to be worked on for extractor before been implemented to Capabilities.

I don't think this will fit in current milestone if what we targeting is cleanup as it's going to require time working on Extractor which I'm not sure it totally worth it right considering adding roles is not something that happen with most plugins.

**Comment by stevejburge** [comment]
@olatechpro OK, thanks.
