### ISSUE TITLE
Redirect on login and logout

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#11]
We could add a feature to CME that sends different users to different URLs when the login and logout

Update: Let provide option to redirect back to original page after login.

**Comment by stevejburge** [comment]
One more request for this today. It could be handed via the "Roles" screen.

**Comment by olatechpro** [comment]
@stevejburge just a confirmation, we're adding option to enter URL that user that belongs to the role should be redirected?

What tab should this be added?

**Comment by stevejburge** [comment]
@olatechpro Correct. I think this should be a new tab when you edit user roles via the "Roles" screen
