### ISSUE TITLE
Show Wordfence capabilities tab for both Wordfence main and Login Security plugin

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#1136]
When you install Wordfence, we show 3 capabilities inside the "Wordfence Security" tab. That's for this plugin: https://wordpress.org/plugins/wordfence/

I think that's a mistake. Those 3 capabilities are for this plugin: 
https://wordpress.org/plugins/wordfence-login-security/

**Comment by olatechpro** [comment]
Those Capabilities are from wordfence main plugin which login security is an addon of and works even without having the separate plugin installed.

![module](https://github.com/user-attachments/assets/70d1e91f-f9d6-44dd-a0b6-c4c14f54cea9)
![Capture](https://github.com/user-attachments/assets/d9093b41-4979-4110-bcd2-ba7eb54fd628)
