### ISSUE TITLE
Prevent unnecesary database updates on init

### ISSUE THREAD

**Issue by rbcorrales** [publishpress/PublishPress-Capabilities#1139]
## Expected Behavior

Updates to the database option `cme_migrated_taxonomy_caps` are not expected on every request.

## Current Behavior

Seeing multiple database updates on every request, like this:

```
UPDATE `wp_options`
SET `option_value` = '1'
WHERE `option_name` = 'cme_migrated_taxonomy_caps'
```

These updates are coming from the `force_distinct_taxonomy_caps` function here:
https://github.com/publishpress/PublishPress-Capabilities/blob/f47504b279570ba6da5be9d60878bc86c69fec88/includes/cap-helper.php#L345

Which is loaded by the `CME_Cap_Helper` class constructor on `init`:
https://github.com/publishpress/PublishPress-Capabilities/blob/f47504b279570ba6da5be9d60878bc86c69fec88/capsman-enhanced.php#L161

## Possible Solution

Use a string instead of a boolean when updating  `cme_migrated_taxonomy_caps` option.
This would prevent sending unneeded updates to the database when calling `update_option()`, as the [WordPress core validation](https://github.com/WordPress/wordpress-develop/blob/6.4.3/src/wp-includes/option.php#L795-L797) will abort updates when the old and new values and their data types are identical (`===`).

## Steps to Reproduce (for bugs)

1. Install and enable [Query Monitor](https://github.com/johnbillion/query-monitor) if not available.
2. Load wp-admin and check the queries, filtering by UPDATE.
3. See the updates listed with this call stack:

```
    update_option
    CME_Cap_Helper->force_distinct_taxonomy_caps
    CME_Cap_Helper->refresh
    CME_Cap_Helper->__construct
    _cme_cap_helper
    do_action
```

## Your Environment

* Version used: 2.10.2
* WP version: 6.3.3

**Comment by stevejburge** [comment]
Thanks for such a detailed report @rbcorrales
