### ISSUE TITLE
Pro: PHP warning about status capabilities

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Capabilities#1143]
PHP Warning: Undefined property: stdClass::$set_posts_status in /nas/content/live/wdwnt/wp-content/plugins/capabilities-pro/lib/status-capabilities/StatusCapabilities.php on line 326

Can we fix this?

Original report: https://secure.helpscout.net/conversation/2474587867/218439?viewId=6932143

**Comment by agapetry** [comment]
https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/db0fe3b73d5ff0cd907c22f907959dfd76270b19
