### ISSUE TITLE
Move multisite settings to sidebar

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#1146]
These are unclear and hard to use:
![capabilities-multisite](https://github.com/publishpress/PublishPress-Capabilities/assets/3868028/5179fcea-74a6-4f36-9ab0-fa3f06b15d1d)

**Comment by olatechpro** [comment]
@stevejburge Do you have a suggestion to improve this other than the way it's currently is?

**Comment by stevejburge** [comment]
@olatechpro Maybe these settings should be in the right sidebar? There they can be clearer and easier to see

**Comment by olatechpro** [comment]
Make sense, will make the update @stevejburge
