### ISSUE TITLE
Better Support for WooCommerce Reports

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#157]
We've had quite a few suggestions along these lines:

> So I want to know if it is possible to create a user role who can only view reports for selected products in woocommerce.
> 
> I have a website and I have suppliers and I want to have a user role who can display woocommerce reports sales only for products for this supplier as by default woocommerce give access to all reports.

**Comment by olatechpro** [comment]
@stevejburge Is this same as https://github.com/publishpress/PublishPress-Capabilities/issues/95 that focus on limiting posts to specific status or https://github.com/publishpress/PublishPress-Capabilities/issues/137 that limit post view based on capabilities or taxonomy?

If so, then we should close this but if not, what's your proposal on implementing this?

**Comment by olatechpro** [comment]
@stevejburge what's your full proposal for this?

This is how current woocommerce report look like:

![report](https://user-images.githubusercontent.com/46832636/183114329-38593333-427d-4d86-9d6e-a8f35531e038.jpg)

**Comment by stevejburge** [comment]
@olatechpro Looking at this, I don't think we'll be able to help these users. 

Reports / Analytics can't be easily modified
