### ISSUE TITLE
Block access to frontend menu links

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#16]
Perhaps related to this for admin menu links: https://github.com/publishpress/Capability-Manager-Enhanced/issues/9

Users want the option of controlling access to frontend menu links

![image](https://user-images.githubusercontent.com/3868028/68239811-ae5fa280-ffd9-11e9-96d4-87f45297f41f.png)

**Comment by agapetry** [comment]
This feature was developed by @olatechpro 
https://github.com/publishpress/PublishPress-Capabilities/pull/90


The following commits were to transfer the code from free to Pro, along with some refactoring by @agapetry :

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/4f322e6cb0992dbea42656b50da3327b4ba86618

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/c83cfe7798516a7509f9590fa9dcbe950fe1bf8c

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/e23585349e5a3e248321b95d0c8abe97c211ba2a

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/354aa6461c13586cb17152d7e0767701f96c1641

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/2eeca4443d096719c37a3114eb215e3fd629e701

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/b5df69a715f43c73b90fe88b17d04af630223bf8


UI Improvements by @htmgarcia :

publishpress/PublishPress-Capabilities-Pro@2edd962


Additional changes by @agapetry :

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/a6bdf3c4c7802a1cbc67ac5da6cced858b60033a
