### ISSUE TITLE
Redesign the "Roles" screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#175]
Let's go full-width with the "Roles" screen:

![Screen Shot 2021-07-07 at 1 40 20 PM](https://user-images.githubusercontent.com/3868028/124806168-615c6e00-df2a-11eb-867d-3b48c3bf3af0.png)

Some key functions can move to the "Roles" screen

- Edit
- Copy (will need text box to enter new name)

This will remove clutter from other screens. These new links can go under the title:

<img width="701" alt="Screen Shot 2021-06-29 at 4 02 20 PM" src="https://user-images.githubusercontent.com/3868028/123860111-7cf4c280-d8f3-11eb-8ff5-cffcd47c9d79.png">

We can add more filters:

<img width="549" alt="Screen Shot 2021-07-07 at 2 10 21 PM" src="https://user-images.githubusercontent.com/3868028/124808604-21e35100-df2d-11eb-9735-3fb43b838098.png">

**Comment by agapetry** [comment]
@stevejburge Copy needs a text entry. Would that be a textbox between the dropdown and the Apply button (revealed when "Copy" is selected)?

**Comment by stevejburge** [comment]
@agapetry Yes, we'd need that

**Comment by olatechpro** [comment]
@stevejburge @agapetry , the requirement on this issue only made mention of adding the new "Add New" button with another issue https://github.com/publishpress/PublishPress-Capabilities/issues/179 focussing more on the new Add/Edit screen.

So, in accordance to that, i'll like the make note of this issue PR only adding the new "Add new" button which will be there as a props with no action until i make another PR for https://github.com/publishpress/PublishPress-Capabilities/issues/179 where it focus on new Add/Edit UI and it won't be possible to work on the issue until this PR is review and probably merged to development.

I'm dropping this note here so it can be referenced on why most of the issues in this milestone depends on this and until it's reviewed, only this issue will be worked on.

**Comment by stevejburge** [comment]
Thanks @olatechpro

**Comment by olatechpro** [comment]
This has been merged
