### ISSUE TITLE
New Add/Edit Box for User Roles

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#179]
@olatechpro Remember your great work with the Taxonomies screen in TaxoPress? Let's do the same for user roles.

This will be one place for all role settings that don't easily fit on other screens.

This can be the layout:
<img width="1209" alt="Screen Shot 2021-07-07 at 1 53 30 PM" src="https://user-images.githubusercontent.com/3868028/124806502-c4e69b80-df2a-11eb-8ba9-d7f57ac117c7.png">

General: 
- "Role Name", can be edited
- "Developer Name, can not be edited

Advanced"
- "Role Level"

Delete
- A big delete button with a warning. Will not apply to Administrators

**Comment by agapetry** [comment]
In my opinion, "Developer Name" is an odd innovation. Aren't people familiar with "slug" from WordPress UI usage?  If not, maybe "Role Label" and "Role ID" ?

![image](https://user-images.githubusercontent.com/43488774/124956274-d345bd80-dfe5-11eb-8300-fd5ace641bc2.png)
