### ISSUE TITLE
Add the option to rename roles

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#18]
It should be possible to rename an existing role. 

Here's the User Role Editor plugin:
<img width="486" alt="Screen Shot 2019-12-13 at 2 40 15 PM" src="https://user-images.githubusercontent.com/3868028/70827088-81f82c80-1db6-11ea-9aef-aa1e82f1ef4d.png">

**Comment by stevejburge** [comment]
One more: 

> Can you edit the role name once it's been created? I don't see a way to do it.

**Comment by agapetry** [comment]
@stevejburge The User Role Editor solution is to keep the actual role name non-editable but allow the display name to diverge from it.  So if you set the subscriber Display name to "Club Member", the users.php filter argument is still ?role=subscriber while the link caption and corresponding dropdown elements are displayed as Club Member.  Is that what you have in mind?

**Comment by stevejburge** [comment]
@agapetry Listening to our users, I think they'd be 100% fine with a purely visual change.

**Comment by stevejburge** [comment]
Solved in a recent release
