### ISSUE TITLE
Banner getting people to install Permissions

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#201]
Permissions has this feature that a lot of Capabilities users want.

Let's decide on a clear and obvious way to say:
"Do you want to control permissions for specific posts and pages? Install Permissions"

<img width="831" alt="Screen Shot 2021-08-30 at 4 09 41 PM" src="https://user-images.githubusercontent.com/3868028/131404128-3c116344-d4c2-40f0-896c-e83d625169b0.png">

**Comment by htmgarcia** [comment]
@stevejburge starter proposal for "Read this post" and "Edit this post" accordions:
![Screen Shot 2021-08-30 at 17 31 39](https://user-images.githubusercontent.com/4999794/131414310-3784e27f-ab5f-4279-a98b-726bbee3c937.png)

**Comment by stevejburge** [comment]
@htmgarcia Thanks. I'm thinking this through and wonder what the best approach is.

- Can we show a banner in this part of the site? If we can, will it annoy people?
- Can a banner here be dismissed?

The alternative would be a more traditional notice at the top of the screen, or a new menu in Capabilities.

**Comment by stevejburge** [comment]
Here's the Yoast sidebar:

<img width="1331" alt="Screen Shot 2021-09-01 at 3 55 48 PM" src="https://user-images.githubusercontent.com/3868028/131735624-d71c9c21-6b62-49bc-ad1f-f70b07a3080a.png">

**Comment by htmgarcia** [comment]
@stevejburge starter proposal for the traditional banner. 
The sidebar banner needs to wait until publishpress/PublishPress-Capabilities-Pro#63 is approved and merged.
![Screen Shot 2021-09-01 at 17 45 19](https://user-images.githubusercontent.com/4999794/131755314-43c38eef-cf83-4b6b-b3bb-980fb722ace5.png)

**Comment by htmgarcia** [comment]
@stevejburge banner proposal
![Screen Shot 2021-09-06 at 17 41 37](https://user-images.githubusercontent.com/4999794/132264019-6bfbd98d-6d23-4912-b63d-93e6bd21cf41.png)

**Comment by stevejburge** [comment]
Great, thanks @htmgarcia. We can just include the Free features. We can emphasize here that Permissions is Free

**Comment by htmgarcia** [comment]
@stevejburge updated proposal:
![Screen Shot 2021-09-13 at 12 27 58](https://user-images.githubusercontent.com/4999794/133129565-bd6aff2d-7470-4e07-91c1-4c52fd2385bd.png)

**Comment by stevejburge** [comment]
Awesome, thanks.

- We can remove the "publishing statuses" line
- Maybe use this instead "PublishPress Permissions is 100% free to install from WordPress.org."

**Comment by htmgarcia** [comment]
@stevejburge update:
![Screen Shot 2021-09-13 at 12 43 21](https://user-images.githubusercontent.com/4999794/133131445-484163f9-15d8-47c7-8bc5-dfe140a2c321.png)

**Comment by stevejburge** [comment]
Sorry, my bad. How about this?

Title: Control permissions for individual posts and pages

- Choose who can read and edit each post.
- Allow specific user roles or users to manage each post. 
- PublishPress Permissions is 100% free to install from WordPress.org.

Button: Click here to install PublishPress Permissions for free

Maybe include the banner too as we're going to redirect them here:
/wp-admin/plugin-install.php?s=publishpress permissions control access&tab=search&type=term

![icon-256x256](https://user-images.githubusercontent.com/3868028/133149478-9ba17e1d-c526-4724-8970-4b93e655aa2d.jpg)

**Comment by htmgarcia** [comment]
@stevejburge update:
![Screen Shot 2021-09-13 at 15 49 35](https://user-images.githubusercontent.com/4999794/133154399-b9f59e08-edd8-4f56-9f34-ac4edd764f16.png)

**Comment by stevejburge** [comment]
Yes, I think that works

- Can we put the banner under the button?
- Let's link the button and the image

**Comment by htmgarcia** [comment]
![Screen Shot 2021-09-13 at 15 59 23](https://user-images.githubusercontent.com/4999794/133155642-8aeceedc-5d7b-4ef8-881f-e7273e26a089.png)

**Comment by stevejburge** [comment]
@htmgarcia 
Awesome, thanks

**Comment by stevejburge** [comment]
@htmgarcia I see this now, which doesn't look quite right:
<img width="1322" alt="Screen Shot 2021-11-05 at 7 45 30 AM" src="https://user-images.githubusercontent.com/3868028/140505646-ddca9a32-fec6-4a93-b320-430987e0d107.png">

**Comment by stevejburge** [comment]
The link is going to the wrong place also:
<img width="1222" alt="Screen Shot 2021-11-05 at 8 34 04 AM" src="https://user-images.githubusercontent.com/3868028/140510891-247634ce-baf2-4aa5-bde4-fba41b5be800.png">

**Comment by htmgarcia** [comment]
@stevejburge the green color in button seems to be coming from another place. 
About the link, should point to the same screen but with "publishpress permissions" words only in the search box?

**Comment by stevejburge** [comment]
@htmgarcia Ah, I see earlier in the thread where this banner slipped in. Sorry, I missed it and focused on the rest of the conversation.

I think we should try and replicate the review request banners. If people see the plugin icon, they'll know which one to install

Maybe try "press-permit-core" for the search term

**Comment by htmgarcia** [comment]
@stevejburge fix #243

**Comment by stevejburge** [comment]
@htmgarcia I've been thinking about this and the WordPress search is funky.

I think our best best is to use a really unusual search term such as "ppcore-install". I can put that text in the readme file. That's the only way to make sure only only plugin shows up.

<img width="916" alt="Screen Shot 2021-11-08 at 11 17 28 AM" src="https://user-images.githubusercontent.com/3868028/140778529-c8aa97a1-c3dc-44e2-93e2-29043cd488a4.png">

**Comment by htmgarcia** [comment]
@stevejburge want me to change the search term to "ppcore-install"?

**Comment by stevejburge** [comment]
@htmgarcia Let's make these even more specific:

"publishpress-ppcore-install"

Can you post a quick screenshot of the top banner we'll use?

**Comment by htmgarcia** [comment]
@stevejburge ![Screen Shot 2021-11-08 at 10 46 25](https://user-images.githubusercontent.com/4999794/140783279-0f8c3a34-4c38-4401-aa4e-4f4dadc466db.png)

**Comment by stevejburge** [comment]
Thanks @htmgarcia. Can we use the same style we use for the review banners? More text and the plugin icon on the right?

**Comment by htmgarcia** [comment]
@stevejburge not sure about the text:
![Screen Shot 2021-11-08 at 11 37 27](https://user-images.githubusercontent.com/4999794/140790865-2bd89422-20d5-4733-8261-9f6ae600bde5.png)

**Comment by stevejburge** [comment]
Can we re-use most of this?

![image](https://user-images.githubusercontent.com/3868028/140791422-fde73aee-6332-4df2-9b62-df4aa0c3973c.png)

**Comment by htmgarcia** [comment]
@stevejburge updated proposal:
![Screen Shot 2021-11-08 at 13 55 41](https://user-images.githubusercontent.com/4999794/140808956-f8da2d62-ab08-4102-a814-df0750af4546.png)

**Comment by stevejburge** [comment]
@htmgarcia looks great, thanks

**Comment by htmgarcia** [comment]
@stevejburge does the readme.txt from Github already include "publishpress-ppcore-install"? Let me know how to integrate it.

**Comment by stevejburge** [comment]
@htmgarcia Yes, it's live now on the main repo at least:
https://wordpress.org/plugins/search/publishpress-ppcore-install/

It may be cached for individual sites

**Comment by htmgarcia** [comment]
@stevejburge inside the admin doesn't work. Maybe a delay? I'll wait until I'm able to reach the same result from WordPress.org
![Screen Shot 2021-11-08 at 16 10 55](https://user-images.githubusercontent.com/4999794/140826317-09a9b904-38a5-42d0-aa03-6cdf7958e6c2.png)

**Comment by stevejburge** [comment]
Yes, it's cached

**Comment by htmgarcia** [comment]
@stevejburge taking the approach to remove the horizontal banner and use instead the one on the sidebar, this is the starter proposal in backups page:
![Screen Shot 2021-11-15 at 20 53 45](https://user-images.githubusercontent.com/4999794/141887460-393f14da-7924-41f5-a56b-24186ad3a380.png)
Is ok to display it in all the pages, excluding the main one?

**Comment by stevejburge** [comment]
@htmgarcia Looks great. Let's include this on every Free screen where we have room
