### ISSUE TITLE
Improve the "list" capabilities display

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#206]
Here's something that we should work into the Capabilities UI in the same manner as Read and Edit:

![image](https://user-images.githubusercontent.com/3868028/133639278-f9362818-b3e1-4779-97d6-20b3d4c8ffe0.png)

Right now, it has to be done manually
https://publishpress.com/blog/hide-peoples-posts-wordpress-admin/

**Comment by olatechpro** [comment]
@stevejburge I don't understand this screen or able to find it.

Wondering if it's an outdated screen?

**Comment by stevejburge** [comment]
@agapetry @olatechpro It has changed a little, yes

<img width="1244" alt="Screen Shot 2022-07-14 at 9 21 40 AM" src="https://user-images.githubusercontent.com/3868028/178992735-216bd910-1de8-4d26-b065-55a58ed31906.png">

Let's make this a central feature of this milestone. Can we make this list_posts option much easier for users?

Many customer requests are based around controlling this "list" feature for WooCommerce Orders, Reports, and more
