### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#214]
Our error logs are showing this often:

`Warning: Invalid argument supplied for foreach() in /..../public_html/wp-content/plugins/capabilities-pro/includes-pro/library/edd-sl-plugin-updater/EDD_SL_Plugin_Updater.php on line 362`

**Comment by stevejburge** [comment]
@olatechpro Can you check with @andergmartins to see if this needs updating?

**Comment by olatechpro** [comment]
I’m not getting the error in latest update of the library and judging by
the issue been close to 3 months. It’s probably fixed unless we have new
report

**Comment by olatechpro** [comment]
@stevejburge why do we still have this issue opened and in active milestone ?

**Comment by stevejburge** [comment]
@olatechpro OK, closing
