### ISSUE TITLE
Add a search box to find permissions

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#22]
Would be great to have a search box on this page to help find permissions
/wp-admin/admin.php?page=capsman

**Comment by htmgarcia** [comment]
@stevejburge proposal for this feature:
![Screen Shot 2021-11-01 at 17 17 56](https://user-images.githubusercontent.com/4999794/139754578-4f300c77-6db9-4c5e-be71-82d55ef4d104.png)
![Screen Shot 2021-11-01 at 17 18 53](https://user-images.githubusercontent.com/4999794/139754583-d289ea8d-5cf5-4f45-9bca-540916f23b93.png)
![Screen Shot 2021-11-01 at 17 20 09](https://user-images.githubusercontent.com/4999794/139754588-121907f3-b433-4a46-9d98-8d0c33bb8fce.png)

**Comment by stevejburge** [comment]
Thanks @htmgarcia 

Good thinking here. Should the post type be a dropdown?

**Comment by htmgarcia** [comment]
@stevejburge yeah, a dropdown should be more appropriate.
