### ISSUE TITLE
Dashes not numbers for "Admin Features"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#229]
Good:
<img width="419" alt="Screen Shot 2021-10-28 at 5 06 28 PM" src="https://user-images.githubusercontent.com/3868028/139335646-d0816383-4847-490c-b908-4f6078533ffb.png">

Not good, at least IMHO. Those number don't exist in the admin area

<img width="398" alt="Screen Shot 2021-10-28 at 5 05 50 PM" src="https://user-images.githubusercontent.com/3868028/139335702-3d91e42c-be77-4aa8-95e8-26d484c34422.png">

**Comment by stevejburge** [comment]
Thanks @olatechpro. Let's match the "Admin Menus" screen and use dashes, please
<img width="322" alt="Screen Shot 2021-11-01 at 12 44 27 PM" src="https://user-images.githubusercontent.com/3868028/139708360-6962efae-4747-4849-97ce-daf212c2e958.png">

**Comment by olatechpro** [comment]
Noted.
