### ISSUE TITLE
Disable the admin toolbar completely?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#239]
Should we add a chechbox that allows you to disable the whole admin toolbar?
<img width="446" alt="Screen Shot 2021-11-03 at 5 11 39 PM" src="https://user-images.githubusercontent.com/3868028/140193431-fa8e6d10-acbd-40c5-9a1c-65e77ecf0e40.png">

**Comment by agapetry** [comment]
This one didn't make it into the last release.

**Comment by olatechpro** [comment]
It did @agapetry, that's why there's a checkbox of beside "Admin Toolbar" in Admin Features

**Comment by agapetry** [comment]
@olatechpro Oh, right. I see it now.
