### ISSUE TITLE
Disable more items in the WordPress admin area

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#240]
Can we create a new area in "Admin Features" with checkboxes for these?
![Screen Shot 2021-11-03 at 5 20 29 PM](https://user-images.githubusercontent.com/3868028/140195010-5001ac7b-5c1e-4409-8573-5f1ce543d74b.png)

**Comment by olatechpro** [comment]
@stevejburge, should this be added to the dashboard widget section or new section?

If new section, what' be the section name and is the restriction applied to only admin dashboard?

**Comment by olatechpro** [comment]
@stevejburge.... You didn't answer my question on restriction. Is the application only on dashboard page or every admin pages?

**Comment by stevejburge** [comment]
@olatechpro Sorry. Every admin screen, please
