### ISSUE TITLE
New sidebar message about backups

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#248]
I think we need a bigger and more obvious sidebar banner about backups. This seems to be a common issue that people don't realize backups are available

@htmgarcia can we use the same side approach we used for the "Install PublishPress Permissions" sidebar?

![Screen Shot 2021-11-15 at 9 49 19 AM](https://user-images.githubusercontent.com/3868028/141802255-682927df-1405-4673-ac3b-a0b169f34d22.png)

**Comment by htmgarcia** [comment]
@stevejburge starter design proposal:
![Screen Shot 2021-11-17 at 13 26 30](https://user-images.githubusercontent.com/4999794/142269136-cf305254-dac4-4363-ab05-72310af3eabd.png)

**Comment by htmgarcia** [comment]
Maybe a graphic to standout:
![Screen Shot 2021-11-17 at 13 39 11](https://user-images.githubusercontent.com/4999794/142270829-7ba418ad-9909-4b5c-a7f1-00aa25c3d665.png)

**Comment by stevejburge** [comment]
@htmgarcia I think the basic version should be good here, with no image

Title: PublishPress Capabilities is safe to use
Text: This plugin automatically creates a backup whenever you save changes. You can use these backups to
restore an earlier version of your roles and capabilities. 
Button: Go to the Backup feature

**Comment by htmgarcia** [comment]
@stevejburge I need to wait on this one approved and merged first https://github.com/publishpress/PublishPress-Capabilities/pull/247
