### ISSUE TITLE
Support for the "Templates" metabox

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#251]
This was raised here: https://wordpress.org/support/topic/hide-editor-feature-template-in-capabilities/

> while I can find the other tabs in the Editor Features section of Capabilities, I can’t seem to find Template so that I can hide that as well.

> Template absolutely is a core metabox PROVIDED that your theme supports / has defined multiple templates. They can be defined multiple ways

Currently we don't support it in "Editor Features":
<img width="363" alt="Screen Shot 2021-11-22 at 4 16 07 PM" src="https://user-images.githubusercontent.com/3868028/142936529-48f66a87-8f71-47a0-828b-5c319ce6cda9.png">

The Twenty Twenty theme is a good test to see this metabox:
<img width="344" alt="Screen Shot 2021-11-22 at 4 18 36 PM" src="https://user-images.githubusercontent.com/3868028/142936698-d4263704-b220-4b55-beca-e95ed074ad3f.png">

**Comment by CodingSamurai** [comment]
Any ETA on this?
