### ISSUE TITLE
Try vertical tabs similar to the "Capabilities" tab

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#257]
Can we try to organize the "Editor Features" with vertical tabs similar to the "Capabilities" tab

This is probably the only way to deal with all the post types

**Comment by htmgarcia** [comment]
Design proposal. Still needs some design and js fixes.
![Screenshot 2021-12-10 at 14-17-45 Editor Features ‹ WordPress — WordPress](https://user-images.githubusercontent.com/4999794/145636137-2f90339f-21c2-43cb-881a-70e6ae0c10aa.png)

**Comment by stevejburge** [comment]
Thanks @htmgarcia. If this matches the Capabilities screen, it's a good step forward

**Comment by agapetry** [comment]
@stevejburge  @olatechpro If we do this, I think there needs to be some kind of indicator on the post type tabs showing the presence of restrictions.  Otherwise it becomes a lot harder to quickly review a role's configuration.

**Comment by stevejburge** [comment]
@agapetry That make sense. Should we delay this feature to add that? Or should we add the indicator in the next release?

**Comment by agapetry** [comment]
@stevejburge For this reason and also because this is a big change to merge and test by tomorrow afternoon, I vote to delay until 2.4.  It feels like more of a point release change.

**Comment by stevejburge** [comment]
Agreed
