### ISSUE TITLE
Issues with Admin Menus in 2.3.2

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#259]
One reported new issue in 2.3.2

"The dashboard menu will no longer be hidden for editors. I installed version 2.3 in a test page environment and everything is perfect, then installed version 2.3.2 and the error was there."
![Admin](https://user-images.githubusercontent.com/3868028/145590231-58952630-6a9a-4f2a-9417-4b673341c9ca.jpg)
![Redakteur](https://user-images.githubusercontent.com/3868028/145590233-5d6cb209-9068-46d9-bf3c-981273b52634.jpg)

**Comment by stevejburge** [comment]
A second reported issue:

> I updated PublishPress Capabilities Pro to version 2.3.2. After the update, my "Admin Menu Restrictions" seem to have been broken.
> 
> Before the update, my users could only see the features they need to work on WP. However, after the update, the users dashboard is showing a lot more features even though the user do not have access to the feature.
> 
> Here is an example. In the screenshot below, the group this user belongs to is supposed to see only the highlighted features. However, as you can see, other features are displaying here. 
> 
> I notice that this happens when I enable "manage options" under WordPress Core in Role Capabilities. This automatically displays all these other features introduced by different plugins.
> 
> Even though the user receives "You do not have permission to access this page." when they click a link they do not have permission to, I still like to remove these features from their dashboard. 

<img width="656" alt="Screen Shot 2021-12-10 at 9 36 03 AM" src="https://user-images.githubusercontent.com/3868028/145590774-d3ef9fbf-7fdd-49d6-8857-928a45f2b63d.png">

**Comment by stevejburge** [comment]
A third reported issue, again saying the error started after moving from 2.3.0 to 2.3.2

> The settings in Admin menus for Role 'School Admin 2' are not being executed. This was working correctly before we updated the plugin that you sent.

![ME-Calendar-School-admin-view](https://user-images.githubusercontent.com/3868028/145595325-e2f6b2b6-9595-4f80-9676-508130cd481e.jpeg)
![ME-Calendar-admin-menus-settings](https://user-images.githubusercontent.com/3868028/145595327-cebdae62-8b16-4bd5-b045-7b193e89c05b.jpeg)

**Comment by olatechpro** [comment]
Pro PR https://github.com/publishpress/PublishPress-Capabilities-Pro/pull/80
