### ISSUE TITLE
Remove "block pages by URL or"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#266]
<img width="531" alt="Screen Shot 2021-12-10 at 3 03 08 PM" src="https://user-images.githubusercontent.com/3868028/145634693-0f3a2078-46da-43e3-a295-54fa854949db.png">

**Comment by agapetry** [comment]
https://github.com/publishpress/PublishPress-Capabilities-Pro/pull/82/commits/91a80bb0e8ca38d9220bf66d8741808091d4a4b8
