### ISSUE TITLE
Force user roles to use specific editors

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#276]
Could we allow the roles screen to force specific roles to use Gutenberg / Classic Editor / some page buider?

> The documentation for the Classic Editor Plugin includes the following statement "In addition, the Classic Editor plugin includes several filters that let other plugins control the settings, and the editor choice per post and per post type." Have you investigated using these "filters" to implement role based controls, instead of "all or nothing" controls?

**Comment by olatechpro** [comment]
@stevejburge can you provide more information on this feature like:
1.) Location/tab of the settings in role edit screen

2.) Input option type and options (e.g, select dropdown with Gutenberg , Classic Editor etc as option )

**Comment by stevejburge** [comment]
Let's do this after the Roles screen is launched.

I imagine an extra tab inside each role

**Comment by stevejburge** [comment]
@olatechpro I'm thinking could be a new tab when you edit user roles via the "Roles" screen

It could be a simple select box option (it would be possible to choose multiple options)
