### ISSUE TITLE
Fatal error when trying to delete WooCommerce roles

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#277]
Trying to delete WooCommerce roles: 

<img width="804" alt="Screen Shot 2022-01-07 at 10 54 07 AM" src="https://user-images.githubusercontent.com/3868028/148570106-7dad1415-1803-406d-9544-8697dbb5ef3c.png">

Produces a fatal error:
<img width="913" alt="Screen Shot 2022-01-07 at 10 54 13 AM" src="https://user-images.githubusercontent.com/3868028/148570170-a39f79e0-0481-431f-9319-a7a534d5fdeb.png">

**Comment by olatechpro** [comment]
Hi @stevejburge , i don't know if this error is tied to something as i'm unable to recreate it on my installation. Deleted role was deleted without any error.

**Comment by stevejburge** [comment]
@olatechpro Same here - all good currently.

Let's close for now
