### ISSUE TITLE
Stop users from adding characters to avoid URL blocks

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#279]
People can avoid the URL block by just adding &test to the URL

Let's find a way to ignore those extra strings and block the URL

**Comment by olatechpro** [comment]
@stevejburge this need to be well thought of.

For example, there are plugins that structure their permalink like: 
https://example.com/wp-admin/admin.php?page=settings
https://example.com/wp-admin/admin.php?page=settings&section=category
https://example.com/wp-admin/admin.php?page=settings&section=category&subsection=posts

all leading to different pages in the backend.

So, if the intention is to restrict access to https://example.com/wp-admin/admin.php?page=settings which is the main page but grant access to other pages, this new request mean we'll be blocking access to every other pages.

**Comment by stevejburge** [comment]
@olatechpro Good point. Perhaps the best approach is to add a clear warning:

"Please use with caution. This feature can block valid URLs if not used correctly."

**Comment by olatechpro** [comment]
So, we go ahead with the implementation ?

**Comment by stevejburge** [comment]
Yes, please:
- With the warning
- With an exception so that Administrators can always access the "Admin Features" screen

**Comment by olatechpro** [comment]
Is the exception different from this #278 ?

Like, this feature should not be applicable to administrator or you're only making references to #278

**Comment by stevejburge** [comment]
@olatechpro Yes, it's the same thing.

We don't want users to lock themselves out of their own site. Administrators should always be able to access this screen:
/wp-admin/admin.php?page=pp-capabilities-admin-features

**Comment by olatechpro** [comment]
You still don't get my question, this current issue is about stopping users from adding characters to avoid URL blocks and you later said there should be exception for admin.

So, i'm confirming by implication, it mean this implementation will not be applicable to administrator ?

Like, if other role add a parameter or visit permalink that has base of a blocked URL, they'll still be blocked but administrator will not be.

That is, after this fix, you'll not be able to test with administrator account since they're excepted.

**Comment by stevejburge** [comment]
@olatechpro Yes, I think that is a good idea. The administrator role should be allows be able to access "Admin Features" and maybe the whole admin area

**Comment by stevejburge** [comment]
Thanks for such as detailed explanation. @olatechpro 

Maybe this feature should have a clear warning and also a documentation link. We can tell people to use it only as a final measure if all other options do not work?

**Comment by olatechpro** [comment]
Note: This implementation has been improved to avoid lockout from entire admin panel.

For example, 
- https://publishpress.olatech/wp-admin/admin.php?page=st_post_tags will not lock user out of https://publishpress.olatech/wp-admin/admin.php?page=ppma-pro-placeholders-fields even though they shared same base URL but instead,
- https://publishpress.olatech/wp-admin/admin.php?page=st_post_tags will lock user out of https://publishpress.olatech/wp-admin/admin.php?page=st_post_tags&subtab.... which is minimal to only sub tab that shared same parent base.

**Comment by olatechpro** [comment]
Pro PR https://github.com/publishpress/PublishPress-Capabilities-Pro/pull/94
