### ISSUE TITLE
Problems with WooCommerce Analytics and the Admin Menus Feature

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#280]
We've had several reports of the Admin Menus feature not working correctly with WooCommerce, particularly the "Analytics" menu

**Comment by olatechpro** [comment]
@stevejburge , can you confirm if this issue still exists ? I think we dealt with similar issues sometimes ago and here's my screen currently after disabling all menus except main dashboard 

![memu](https://user-images.githubusercontent.com/46832636/153362719-7c147047-31dc-4c0f-b957-93d2798d9e9f.jpg)

**Comment by stevejburge** [comment]
@olatechpro Yes, I can still see this.

In fact, a couple more plugins seem to trigger this, including PublishPress Blocks. In this image, I've blocked access to every admin menu:
![Screen Shot 2022-02-14 at 4 10 31 PM](https://user-images.githubusercontent.com/3868028/153947116-f19fa67a-e365-4797-9bda-9205aee4e626.png)

**Comment by stevejburge** [comment]
@olatechpro This works 99%, but there is some odd behavior

Here's what I see when editing the Admin Menus:
![Screen Shot 2022-02-14 at 4 10 31 PM](https://user-images.githubusercontent.com/3868028/153947358-c4fbe746-1962-4ad6-be21-0eccfe4f3c5d.png)

And here's what I see on other screens:

![Screen Shot 2022-02-14 at 4 14 42 PM](https://user-images.githubusercontent.com/3868028/153947524-9734be3b-138d-4939-acdd-9c4a60c709a3.png)

**Comment by stevejburge** [comment]
thanks @olatechpro 

No worries, we'll keep working and improving this step-by-step. We do always have the "Hide CSS" option for very tricky plugins

**Comment by agapetry** [comment]
@olatechpro Closing with caveats noted.
