### ISSUE TITLE
Export / Import for new features

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#282]
Can we create an the export / import feature?

This can be the same as backup, but downloadable

- Capabilities
- Admin Features
- Admin Menus
-  Editor Features

![Screen Shot 2022-01-18 at 11 00 05 AM](https://user-images.githubusercontent.com/3868028/149972950-f2bf65b7-d1b3-4071-bd4d-11eefa2be0c8.png)

**Comment by olatechpro** [comment]
Merged
