### ISSUE TITLE
Problem with the "Customize" link

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#290]
> I created a custom user role and gave it the edit_theme_options capability. I then went into the Admin Menus area and tried to hide everything under the Appearance menu except for "Menus". However, there are still two links showing under the Appearance menu that I do not want to be there, and they are "Customize" and "Background". How do I hide/block these from this user role?

I can confirm this with a theme that doesn't use Full-Site Editing. Settings:
<img width="368" alt="block-menus" src="https://user-images.githubusercontent.com/3868028/151614310-0346d5a0-a6d2-4342-a6f1-ab9bfb8ca0af.png">

Result:
<img width="351" alt="menus" src="https://user-images.githubusercontent.com/3868028/151614320-28699cb9-7c16-44a9-b0ab-b132135c0c4a.png">

**Comment by olatechpro** [comment]
> ".....I can confirm this with a theme that doesn't use Full-Site Editing. Settings:"


@stevejburge , can you give me sample of theme to test this with, currently not able to replicate this inTwenty-twenty one theme ?

**Comment by stevejburge** [comment]
Hi @olatechpro. Can you try the Astra theme?

**Comment by olatechpro** [comment]
Thanks @stevejburge able to get to the root of the issue now
