### ISSUE TITLE
"Editor Features" support for WooCommerce Orders, Coupons etc

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#299]
This will need some custom work, especially as they are private post types

**Comment by olatechpro** [comment]
@stevejburge I believe this may be outdated as we've made improvement to editor features in the past months which include only displaying post metaboxes and taxonomy for post type if they support it and many more.

So, i'll test an individual and give comment on each status and if there's any further fixes, i'll implement it on this PR

**Comment by olatechpro** [comment]
1. This is for order. Everything in order screen including Order details, action, notes, items are metaboxes and they can be removed via pro metaboxes.

![order](https://user-images.githubusercontent.com/46832636/183063665-9328f9c7-6313-4850-9035-560f8384b8e7.jpg)

So, i believe that's fixes

**Comment by olatechpro** [comment]
2. Same apply for coupon. The only metabox is coupon data which can be hidden in metaboxes.
However, there's need to include coupon description which is currently missing.

![coupon](https://user-images.githubusercontent.com/46832636/183064528-4cbc4130-541d-4d08-86fd-3b6f16b42c99.jpg)

**Comment by stevejburge** [comment]
@olatechpro Thanks. Yes, I think this is solved with this new feature:
<img width="609" alt="Screen Shot 2022-08-05 at 11 36 07 AM" src="https://user-images.githubusercontent.com/3868028/183111675-f5846ac0-4d3c-4ff3-9539-e6d3a185407d.png">
