### ISSUE TITLE
Redirect users to original page after login

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#301]
> I am redirecting restricted users to the login page, but would like to be able to retain reference to what they were attempting to view in order to redirect them there after login. Is there any hook or way to pass this data to the login page, potentially as a query string appended to the redirect url?

https://www.isitwp.com/redirect-back-to-referring-page-after-login/​​​
https://wordpress.stackexchange.com/questions/66974/login-redirect-to-previous-page

**Comment by olatechpro** [comment]
@stevejburge which role tab are we adding this feature?

**Comment by stevejburge** [comment]
Let's add a new tab, "Login Redirect"

**Comment by olatechpro** [comment]
@stevejburge I'm closing this in favour of https://github.com/publishpress/PublishPress-Capabilities/issues/11 as they belong to same group
