### ISSUE TITLE
More categorization for capabilities

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#303]
The "User Roles and Capabilities" plugin" does a good job of categorizing the core capabilities:
<img width="224" alt="Screen Shot 2022-02-22 at 4 12 10 PM" src="https://user-images.githubusercontent.com/3868028/155220384-3fa3e1e2-a536-496c-8f91-f1fbe6ee8e13.png">

This is the Members plugin:

<img width="442" alt="Screen Shot 2022-02-22 at 4 14 13 PM" src="https://user-images.githubusercontent.com/3868028/155220524-923080d2-df30-4d3f-ab2a-5e3f82cee8f5.png">

**Comment by olatechpro** [comment]
@stevejburge i thought we just redesigned capabilities screen to tabbed view? How do you see this fit in or you're simply asking to add more tabs to further categorize the capabilities?

**Comment by stevejburge** [comment]
@olatechpro This will be more tabs here:
![Screen Shot 2022-03-30 at 5 38 26 PM](https://user-images.githubusercontent.com/3868028/160935333-1b28061f-1ec9-4f26-a9c5-23c40bdcfb4e.png)
