### ISSUE TITLE
Add a "Check all boxes" setting on top of "Capabilities areas

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#304]
Lots of Capabilities screens have a "Check all boxes" option

![Screen Shot 2022-02-23 at 10 41 40 AM](https://user-images.githubusercontent.com/3868028/155353697-c1d16978-e5a6-4922-969b-e5cc3326d752.png)

Can we add that for tabs such as "WordPress core"?
<img width="1068" alt="Screen Shot 2022-02-23 at 10 42 39 AM" src="https://user-images.githubusercontent.com/3868028/155353840-c1eb9895-bec4-4974-b2c3-b824567ca4f1.png">

**Comment by olatechpro** [comment]
@stevejburge tabs like "WordPress Core" actually have this checkbox that allow to select/deselect all already even though it's at the bottom.

I'm wondering if the changes was made for this issue while it remain opened or there is new requirement and we should move the checkbox to the top instead?

**Comment by stevejburge** [comment]
Yes, let's do the top also, please

**Comment by agapetry** [comment]
This was merged into 2.3.5, but @stevejburge is still looking for more standard styling and behavior from the bulk-negate / bulk-un-negate buttons.

**Comment by stevejburge** [comment]
@agapetry Thanks. Let's close this and then open a new issue as we work on UI improvements
