### ISSUE TITLE
Minimize the sidebar on the Capabilities screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#31]
We need a genuine "Settings" area in the Free version, not just Pro

This can hold the license key, plus also lots of these settings:

<img width="271" alt="Screen Shot 2020-03-09 at 10 52 25 AM" src="https://user-images.githubusercontent.com/3868028/76226365-26421180-61f4-11ea-9063-dc203cee5ced.png">

**Comment by stevejburge** [comment]
Here's an example of this sidebar getting a little out-of-control:
![Screen Shot 2022-11-03 at 3 07 26 PM](https://user-images.githubusercontent.com/3868028/199812312-580bbdf3-1aa3-42a0-9210-999334cc5429.png)

**Comment by olatechpro** [comment]
### From Slack

**Steve:**
On a busy site, these boxes can get very very long
I wonder .... could we hide them? Perhaps in a Gutenberg-style metabox?
