### ISSUE TITLE
Inconsistencies with language files

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#311]
The developer helping with translations ( https://github.com/publishpress/PublishPress-Capabilities/issues/310 ) has a bug report: 

> 1- inside the ...\wp-content\languages\plugins folder are labelled "capability-manager-enhanced-it_IT.po"
> 
> 2- inside the capability-manager-enhanced folder are labelled "capsman-enhanced-it_IT.po"
> 
> I think this can create confusion but I am not a developer.

We should choose one approach and stick with it?

**Comment by agapetry** [comment]
@stevejburge This will require changing the language argument in every translation call (429 instances in 14 files) from 'capsman-enhanced' to 'capability-manager-enhanced'

@olatechpro This will complicate change merging if you are already working on extensive changes.  Please let me know when you see a good time to do this.

**Comment by stevejburge** [comment]
@agapetry Thanks. I guess this is needed to fix a legacy issue, but we can move to 2.6
