### ISSUE TITLE
UI clean up for Backup screens

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#322]
@htmgarcia Can you help Ola with some UI clean up on the "Backup" screens in PublishPress. They are quite inconsistent

<img width="1194" alt="Screen Shot 2022-03-24 at 3 30 53 PM" src="https://user-images.githubusercontent.com/3868028/159995738-a76fcd7b-8c6a-4f33-b674-d2b94b7a33af.png">
<img width="1207" alt="Screen Shot 2022-03-24 at 3 31 02 PM" src="https://user-images.githubusercontent.com/3868028/159995744-b725137f-4154-4bfb-819d-9e615e71e68d.png">
<img width="1218" alt="Screen Shot 2022-03-24 at 3 31 07 PM" src="https://user-images.githubusercontent.com/3868028/159995745-9ca7c657-cdea-4fd9-9f70-48b9fcc50404.png">
<img width="1213" alt="Screen Shot 2022-03-24 at 3 31 11 PM" src="https://user-images.githubusercontent.com/3868028/159995747-c5c314ac-b20a-4ae3-a62f-ca5ffffc5602.png">

**Comment by htmgarcia** [comment]
@olatechpro which branch should I use as base to work on this task?

**Comment by olatechpro** [comment]
Development @htmgarcia

**Comment by olatechpro** [comment]
@htmgarcia kindly remember to check this if you have time

**Comment by htmgarcia** [comment]
@stevejburge @olatechpro starter proposal:
![Screen Shot 2022-05-18 at 16 38 45](https://user-images.githubusercontent.com/4999794/169160842-0a9b5721-ec2a-4786-bdbb-e7ab60ce57ef.png)
![Screen Shot 2022-05-18 at 16 38 39](https://user-images.githubusercontent.com/4999794/169160843-d12305e4-d5f0-4084-bcb4-8579e06367b6.png)
![Screen Shot 2022-05-18 at 16 38 33](https://user-images.githubusercontent.com/4999794/169160846-a5b8b1e5-882a-4030-bb38-18bc478a00a2.png)
![Screen Shot 2022-05-18 at 16 38 27](https://user-images.githubusercontent.com/4999794/169160849-ebee2ab5-8706-4c2d-b512-672830ebcd13.png)

**Comment by stevejburge** [comment]
@htmgarcia Thanks. It's very helpful to see them in this view

For some reason, I feel like these could be cleaner. We have a real mix of different widths, font weights, and more:


<img width="804" alt="Screen Shot 2022-05-19 at 11 20 30 AM" src="https://user-images.githubusercontent.com/3868028/169334494-59f5c647-d4f8-46ab-80a1-6419511076da.png">

**Comment by htmgarcia** [comment]
@stevejburge I made some adjustments:
![Screen Shot 2022-05-19 at 11 48 14](https://user-images.githubusercontent.com/4999794/169354612-6875bf74-e8b4-4699-a204-8d85bc9ee832.png)
![Screen Shot 2022-05-19 at 11 48 07](https://user-images.githubusercontent.com/4999794/169354613-b01b7d83-dd4c-4c88-9e90-7a63717f3c07.png)
![Screen Shot 2022-05-19 at 11 48 00](https://user-images.githubusercontent.com/4999794/169354618-bd0e94c8-7f13-4c97-a5be-154dddfbe294.png)
![Screen Shot 2022-05-19 at 11 47 55](https://user-images.githubusercontent.com/4999794/169354622-da3944a0-36e1-4530-a4d1-0e27f3df5914.png)

I feel we are using too much yellow buttons
![Screen Shot 2022-05-19 at 11 47 36](https://user-images.githubusercontent.com/4999794/169354753-825b5a56-099a-4250-b64a-df2fe97f42eb.png)
. Maybe change some to default WP?

**Comment by stevejburge** [comment]
@htmgarcia Thanks, that looks better

I agree on the yellow. We should keep that only for the most important buttons

**Comment by htmgarcia** [comment]
@stevejburge I correct myself, this should be the button style (blue background), not the one with border:
![Screen Shot 2022-05-19 at 14 47 36](https://user-images.githubusercontent.com/4999794/169391778-10be6dff-6fd4-409c-b61c-bf7e70531fa8.png)

**Comment by htmgarcia** [comment]
@stevejburge opened a new issue https://github.com/publishpress/PublishPress-Capabilities/issues/440

**Comment by stevejburge** [comment]
@htmgarcia thanks

**Comment by htmgarcia** [comment]
@olatechpro do I require to implement the same changes to Pro repository?

**Comment by olatechpro** [comment]
I clone changes from free to pro at the point of release. So, no need unless there’s pro specific changes. @htmgarcia
