### ISSUE TITLE
Capabilities Settings is an empty tab

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#324]
<img width="637" alt="Screen Shot 2022-03-24 at 3 50 04 PM" src="https://user-images.githubusercontent.com/3868028/159998625-b16ef660-1950-4026-83b6-502e0269c5e3.png">

**Comment by olatechpro** [comment]
Note: The capability tab content only display if there's PP_Custom_Status class. So, i only update it to remove the tab

**Comment by olatechpro** [comment]
PRO PR https://github.com/publishpress/PublishPress-Capabilities-Pro/pull/98
