### ISSUE TITLE
Small UI changes to new Roles screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#325]
![Screen Shot 2022-03-24 at 3 54 37 PM](https://user-images.githubusercontent.com/3868028/160000048-b365f507-bc03-48d5-88fa-5ea0786babb4.png)

**Comment by agapetry** [comment]
@stevejburge Also, the "Editing copied role" caption should either change or go away. I think it's actually redundant.

**Comment by olatechpro** [comment]
The following caption are added based on condition:
- Editing role > When editing a role
- Editing copied role > When editing copied role/after a role is copied for editing before update
- Add new role > When adding new role.

So, do you need me to remove the title completely or only made update for specific one or all and if so, kindly help with new text update

@stevejburge

**Comment by stevejburge** [comment]
Thanks @olatechpro @agapetry. Yes, let's replace "Manage Roles" with a new title that explains the current situation
