### ISSUE TITLE
Small UI clean up on "Capabilities" screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#327]
<img width="504" alt="Screen Shot 2022-03-24 at 3 18 00 PM" src="https://user-images.githubusercontent.com/3868028/160000636-62830cd4-3c7b-42c7-8951-0fdad173a568.png">

- Remove "Recommendations for you"
- Use this style for the button:
<img width="126" alt="Screen Shot 2022-03-24 at 3 19 09 PM" src="https://user-images.githubusercontent.com/3868028/160000682-64a16734-69be-4122-b151-4d88c0fa8db0.png">

**Comment by olatechpro** [comment]
@stevejburge the banner appears on Capabilities, backup, admin features, and editor features screen.

Do you need me to make this update on all screen or just the capabilities screen?

**Comment by stevejburge** [comment]
@olatechpro This banner should just appear on the Capabilities screen, please. That's the only part that can not be undone with just a click

**Comment by olatechpro** [comment]
The places i mentioned above is where the banner are currently. So, i’m
asking if i should made the update to all the places with the banner or
only capabilities screen.

**Comment by stevejburge** [comment]
If it's in other places, let's remove it, please.

This banner is only needed on the Capabilities screen

**Comment by olatechpro** [comment]
@stevejburge i thought it was same banner on those pages before but on closer look, the banners are different even though they're same styles. So, i'll simply update the capabilities screen banner and after checking if you need update made to other pages that has different banner, you can add an issue on it.
