### ISSUE TITLE
More details on Roles screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#328]
Let's expand this Roles screen with more key details.

Each row can have these:

- Link to Capabilities
- Link to Edit Features 
- Link to Admin Features 

We can remove the "Role" column

<img width="1227" alt="Screen Shot 2022-03-24 at 4 04 24 PM" src="https://user-images.githubusercontent.com/3868028/160001115-88ee7f96-fd14-45c2-9908-46b932a820d9.png">

**Comment by olatechpro** [comment]
@stevejburge is this different from https://github.com/publishpress/PublishPress-Capabilities/issues/181 ?

**Comment by stevejburge** [comment]
@olatechpro No, sorry. These are the same issue. Let's go with 181 for now
