### ISSUE TITLE
Multisite: should we expose the Super Admin role for editing

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#329]
<img width="606" alt="Screen Shot 2022-03-24 at 4 40 16 PM" src="https://user-images.githubusercontent.com/3868028/160006512-b6801fbb-9fa2-485c-ba81-5f1ea64208c9.png">

**Comment by olatechpro** [comment]
@stevejburge  Super Admin Priviledge is not a role and neither does it have any relation to do with global role but rather a Priviledge that's granted to user. So, nothing like Super Admin role and capabilities.

**Comment by stevejburge** [comment]
@olatechpro thanks
