### ISSUE TITLE
Create a New Roles Screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#33]
This Roles screen should have it's own menu link under "Capabilities"

It does not need a "Clone" link but it should have a "Capabilities" link so people can edit the permissions on the main /wp-admin/users.php?page=capsman screen

It does not need the Granted or Denied column.

<img width="948" alt="Screen Shot 2020-03-09 at 11 00 29 AM" src="https://user-images.githubusercontent.com/3868028/76227148-39a1ac80-61f5-11ea-9cf1-db5ce57d7422.png">

**Comment by agapetry** [comment]
If Valentin is focusing on CSS, this one should be assigned to me.

**Comment by stevejburge** [comment]
Thanks @agapetry

**Comment by agapetry** [comment]
This feature was developed by @olatechpro :
https://github.com/publishpress/PublishPress-Capabilities/pull/91

... with some back-end changes and refactoring by @agapetry. The "Add New" handler now calls existing code as used on the Capabilities screen.  Separate Role and Name boxes are replaced with a single entry, with role slug auto-generated from Name.

https://github.com/publishpress/PublishPress-Capabilities/commit/e65376abdde1b3bef252b212df06f44f55222f2d

https://github.com/publishpress/PublishPress-Capabilities/commit/97cc84932585a57c5b45f829cf2113b4b9e6780a


Additional changes by @agapetry 

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/4dd8d9b70be4d4f0bb706b4c5e33c16672399376

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/d292248d520152293100072ea7b2d9969c26dacc

https://github.com/publishpress/PublishPress-Capabilities/commit/0e5697c9929e54c64bf1d7024ea577c0bb8c85dd
