### ISSUE TITLE
Can't hide the "Profile" link with "Admin Menus"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#337]
I'm not sure if this is because the "Profile" link changes location for users such as Authors:

![Screen Shot 2022-04-04 at 3 13 20 PM](https://user-images.githubusercontent.com/3868028/161615436-9cb87a88-b4f3-4d4e-bffc-96db6031ca9f.png)

**Comment by olatechpro** [comment]
@stevejburge can you provide more information on 

> "I'm not sure if this is because the "Profile" link changes location for users such as Authors:"

I tested it in environment where authors was active but not able to recreate the issue.

**Comment by olatechpro** [comment]
@stevejburge can you provide more information on

`"I'm not sure if this is because the "Profile" link changes location for users such as Authors:"`

I tested it in environment where authors was active but not able to recreate the issue.

**Comment by olatechpro** [comment]
Okay, this is tricky because the users that was hidden wasn't same as the "Profile Link" that's available for Authors.

How do you feel we should implement such a fix?

Should we check if users is hiding and hide the profile for other role?

**Comment by olatechpro** [comment]
PRO PR https://github.com/publishpress/PublishPress-Capabilities-Pro/pull/100

**Comment by olatechpro** [comment]
This has been merged
