### ISSUE TITLE
WooCommerce not disabling a couple of metaboxes

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#390]
If you disable everything in "Products" for "Editor Features" you are still left with 2 boxes:
![Screen Shot 2022-04-28 at 9 22 26 AM](https://user-images.githubusercontent.com/3868028/165762108-abdbeca9-2a8e-4270-a4cb-b44a4588d36a.png)

![Screen Shot 2022-04-28 at 9 23 16 AM](https://user-images.githubusercontent.com/3868028/165762135-19d30f53-e507-492d-b162-33300c6ce41a.png)

**Comment by olatechpro** [comment]
![product-mb](https://user-images.githubusercontent.com/46832636/167390983-ab0254ed-672c-44e4-8a68-30d2b6285759.jpg)

@stevejburge
1.) Product data and Product gallery are metabox and as a result, only available in pro.

2.) Do you have "Product data" and "Product gallery" in the Editor features metabox list as in the attached screenshot? If No, that shows you haven't visit the product edit page (wp-admin/post-new.php?post_type=product) before updating the metabox as we relied on user visiting the cpt screen before saving the available metabox.

**Comment by stevejburge** [comment]
OK, thanks @olatechpro. Let's close this and re-open if users report it
