### ISSUE TITLE
Can Admin Features cover the admin toolbar?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#391]
Can we extend the CSS element blocking feature so it can remove items in the admin toolbar.

For example, I'm having a hard time removing this Avada theme link (Edit Live) for a user:

![Screen Shot 2022-04-28 at 11 19 28 AM](https://user-images.githubusercontent.com/3868028/165786733-8c713e7c-9dcf-4de5-92b3-f8c7036246c7.png)

More details on this Avada issue: https://theme-fusion.com/forums/topic/remove-edit-live-option-from-menu/

**Comment by olatechpro** [comment]
@stevejburge we already have the "Admin Toolbar" that remove the whole admin toolbar but i understand this feature request is to enable removing the admin toolbar content using the Pro "Hide Css Element" feature?

If so, the CSS element blocking feature doesn't have default option and it's as simple as inspecting the page element to find the css selector of the element you want to hide.

For example, adding #wp-admin-bar-query-monitor will remove query monitor and `#wp-admin-bar-fb-edit` will remove avada theme `Edit Live`


Or is there something you want us to do for some circumstances? @stevejburge

**Comment by stevejburge** [comment]
@olatechpro Thanks. Consider this one closed then
