### ISSUE TITLE
Support for a new image capabilitity in WordPress 6.0

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#401]
edit_custom_thumbnail_sizes

Overview: https://make.wordpress.org/core/2022/05/03/wordpress-6-0-field-guide/

Ticket: https://core.trac.wordpress.org/ticket/28277

**Comment by olatechpro** [comment]
@stevejburge i'm not sure i understand the scope of this request. Support for image capability? Perhaps you should provide more clarification like where are we putting this feature, what are the options and what's it suppose to do?

That'll help me in understanding this request.

**Comment by olatechpro** [comment]
@stevejburge i searched the `edit_custom_thumbnail_sizes` you mentioned and it's a filter and not capability. Perhaps you should explain how you want this to be available as capability option since filters is not same as capabilities?

**Comment by stevejburge** [comment]
Hi @olatechpro. Sorry, this is probably a good example of my communication that Kevin mentioned yesterday. I threw this up as a quick idea. We can ignore this :)
