### ISSUE TITLE
How to handle checkmarks and Xs on the Capabilities screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#419]
Can we look at how to handle checkmarks and Xs on the Capabilities screen?

- It seems impossible to add an X to a box, unless you add a box to all the Xs. Can we make it possible to add an X to one box?

![Screen Shot 2022-05-09 at 12 01 10 PM](https://user-images.githubusercontent.com/3868028/167450558-e0e37fb3-c34b-4656-a3ea-b2a6113e9966.png)

- Why is X the only option that can be added to all boxes? Can we all checkmarks to be added to a whole row? Or should we handle this with columns, as on the other parts of the "Capabilities" screen?
![Screen Shot 2022-05-09 at 12 01 10 PM](https://user-images.githubusercontent.com/3868028/167450908-50e4170c-91e9-47c8-ad9b-8e1bae835ab3.png)

**Comment by olatechpro** [comment]
![x](https://user-images.githubusercontent.com/46832636/167889041-6e8ffb21-43cf-4888-ab0c-fd2cd28b8db3.jpg)


@stevejburge just to be clear, the 'X' in front of Posts and Pages circled in the above screenshot should be added to every column top as highlighted in the screenshot?

**Comment by stevejburge** [comment]
@olatechpro Good question. This might require some thought. Maybe it's too busy in the table headers and we add a checkmark to the row, next to the X?

Certainly I think clicking in the box should rotate between X, checkmark, and blank

**Comment by olatechpro** [comment]
@stevejburge what's the proposed solution for the first statement in the issue description or it should be ignored?

> It seems impossible to add an X to a box, unless you add a box to all the Xs. Can we make it possible to add an X to one box?

You proposed a solution to add checkbox after the X to rotate between marking as X, checking the checkbox and changing it uncheck box but didn't make comment on the first issue.

**Comment by stevejburge** [comment]
@olatechpro Clicking the titles? Wow. I've used the plugin for 3 years and never realized that :) It is definitely too hard to find.

I do think we should have a checkmark next to the X, please

**Comment by olatechpro** [comment]
Okay @stevejburge
