### ISSUE TITLE
Cause PHP error and cannot login back to admin

### ISSUE THREAD

**Issue by kartery** [publishpress/PublishPress-Capabilities#426]
Hi developers, 

It is much appreciated for creating the plugin, it helps a lot on my work.  I want to report a bug after updating the capability-manager-enhanced plugin to v.2.4.1, the following error message is displayed in the error log.  I hope that it may help for fixing any issues for the others.

PHP Parse error:  syntax error, unexpected '(' in /....../wp-content/plugins/capability-manager-enhanced/vendor/composer/autoload_real.php on line 32

On-screen shows:
There has been a critical error on this website. please check your site admin email inbox for instructions. learn more about troubleshooting WordPress.

Need manually renew the plugin folder "capability-manager-enhanced" to deactivate the plugin, and it cannot be activated after being reinstalled.

WordPress v5.9
PHP v7.4.28

**Comment by olatechpro** [comment]
Hi @kartery can you attach the copy of your site /capability-manager-enhanced/vendor/composer/autoload_real.php?

**Comment by kartery** [comment]
# cat wp-content/plugins/capability-manager-enhanced/vendor/composer/autoload_real.php                                                                                                                 <?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit94bd22b5e0f1f0f3ce6feebfa626e892
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit94bd22b5e0f1f0f3ce6feebfa626e892', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit94bd22b5e0f1f0f3ce6feebfa626e892', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        \Composer\Autoload\ComposerStaticInit94bd22b5e0f1f0f3ce6feebfa626e892::getInitializer($loader)();

        $loader->register(true);

        $includeFiles = \Composer\Autoload\ComposerStaticInit94bd22b5e0f1f0f3ce6feebfa626e892::$files;
        foreach ($includeFiles as $fileIdentifier => $file) {
            composerRequire94bd22b5e0f1f0f3ce6feebfa626e892($fileIdentifier, $file);
        }

        return $loader;
    }
}

/**
 * @param string $fileIdentifier
 * @param string $file
 * @return void
 */
function composerRequire94bd22b5e0f1f0f3ce6feebfa626e892($fileIdentifier, $file)
{
    if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
        $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

        require $file;
    }
}

**Comment by kartery** [comment]
@olatechpro The content listed as below

< autoload_real.php>

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit94bd22b5e0f1f0f3ce6feebfa626e892
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit94bd22b5e0f1f0f3ce6feebfa626e892', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit94bd22b5e0f1f0f3ce6feebfa626e892', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        \Composer\Autoload\ComposerStaticInit94bd22b5e0f1f0f3ce6feebfa626e892::getInitializer($loader)();

        $loader->register(true);

        $includeFiles = \Composer\Autoload\ComposerStaticInit94bd22b5e0f1f0f3ce6feebfa626e892::$files;
        foreach ($includeFiles as $fileIdentifier => $file) {
            composerRequire94bd22b5e0f1f0f3ce6feebfa626e892($fileIdentifier, $file);
        }

        return $loader;
    }
}

/**
 * @param string $fileIdentifier
 * @param string $file
 * @return void
 */
function composerRequire94bd22b5e0f1f0f3ce6feebfa626e892($fileIdentifier, $file)
{
    if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
        $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

        require $file;
    }
}

**Comment by olatechpro** [comment]
Thanks @kartery

**Comment by kartery** [comment]
> Thanks @kartery

Hi @olatechpro, do you have any work around that I can try to work on?  Since it is one of main functions that while deploy the wordpress.

**Comment by olatechpro** [comment]
@kartery apologies for the delay, this issue will be fixed in the next release but pending the time, i've packaged a working version for you and you can download and replace the plugin with this one to fix the issue pending the time official release will be out https://drive.google.com/file/d/1Yn7v97Ro0f-6qkz196uerOB0H60Gn4IP/view?usp=sharing
