### ISSUE TITLE
Correct match of post types and Editor Features boxes

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#427]
I've a test site with Easy Digital Downloads and WooCommerce installed.

On the "Posts" tab of "Editor Features", the boxes for those plugins appear. Can we patch post types to the correct boxes?
<img width="954" alt="Screen Shot 2022-05-13 at 2 19 40 PM" src="https://user-images.githubusercontent.com/3868028/168343999-0c16a492-9694-4593-902d-8cc58a852b1f.png">

**Comment by olatechpro** [comment]
### Note:

This should be extended to Metabox that exists in Pro version
