### ISSUE TITLE
Admin Features UI design consistency

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Capabilities#466]
Admin Features menu.
Buttons and input fields
![Screen Shot 2022-06-03 at 11 38 04](https://user-images.githubusercontent.com/4999794/171908468-73bb2694-f8a4-436d-84d3-2c9c5de36549.png)

**Comment by stevejburge** [comment]
Thanks @htmgarcia 

I think this part of the screen could be a cleaner. Could you have a go at clean in this CSS Element and Block URL area?

**Comment by htmgarcia** [comment]
@stevejburge @agapetry proposed design:
![Screen Shot 2022-06-30 at 13 09 19](https://user-images.githubusercontent.com/4999794/176747971-14daad19-8986-4e6b-bd06-e934f1f3a4c4.png)

**Comment by stevejburge** [comment]
Thanks @htmgarcia That's good progress

@olatechpro I'm also going to suggest some text changes, please. For example "CSS" instead of "Css". Should I open another issue?

**Comment by olatechpro** [comment]
No need @stevejburge that's a minor fix that goes with the issue.

Thanks @htmgarcia will check the PR
