### ISSUE TITLE
unfiltered_html not working on multisite

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#467]
I confirmed this in my testing:

> I'm using the Capabilities plugin on a Multisite network and I'm having trouble with the the unfiltered_html feature. As your article indicates here ( https://publishpress.com/knowledge-base/unfiltered_html/ ) on a Multisite network only the Super Admin has that capability (despite the Editor role, for example, having that checked as well). This is creating a lot of issues for our users, as every time they edit a page with an iframe embedded, it gets stripped

**Comment by olatechpro** [comment]
@stevejburge a capability not working is not the capability plugin problem. The plugin only assign and un-assign capabilities and nothing more. Either it work or not depends on code that uses it implementation.

I'll search and find related issue to further support what could be wrong but still, nothing can be done from capabilities assignment end.

**Comment by olatechpro** [comment]
@stevejburge i took some time to trace core code and i can confirm that WordPress has a global override in the method `map_meta_cap()` in `wp-includes/capabilities.php`, which ignores the `unfiltered_html` capability in a multisite install if the user is not a super admin.

The code is in `Line 425 of wp-includes/capabilities.php` and here's screenshot.

![wp-unflitered](https://user-images.githubusercontent.com/46832636/176900861-8210d3aa-e67a-4f2b-bd18-aa081f9a9832.jpg)

On possible solution. Yes, it's possible to overwrite this but this is out of capabilities plugin context to force certain capabilities irrespective of the function usage. However, one of the following code will fix the issue for the site.

1. 
```
// Remove KSES if user has unfiltered_html cap
function umc_ustom_kses_init() {
    if ( current_user_can( 'unfiltered_html' ) ) {
		kses_remove_filters();
    }
}
add_action( 'init', 'umc_ustom_kses_init', 11 );
add_action( 'set_current_user', 'umc_ustom_kses_init', 11 );
```

OR

2. 

```
function multisite_restore_unfiltered_html($caps, $cap, $user_id, $args ) {
    if ( 'unfiltered_html' === $cap && user_can( $user_id, 'unfiltered_html' ) )  {
        $caps = array( 'unfiltered_html' );
    }

    return $caps;
}
add_filter( 'map_meta_cap', 'multisite_restore_unfiltered_html', 1, 4 );
```


So, will this work or you want us to add it to capability plugin @stevejburge

**Comment by stevejburge** [comment]
@olatechpro No worries. This is best as documentation
