### ISSUE TITLE
Checkbox for the "Allowed Editors" feature

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#498]
Can we use a checkbox for the "Allowed Editors" feature?

At the moment, the usability isn't 100% clear.

Label: "Control which editors are available to users in this role".
<img width="834" alt="Screen Shot 2022-06-22 at 4 07 28 PM" src="https://user-images.githubusercontent.com/3868028/175126867-f1a24d8c-3143-4ae2-9869-7ab1f6493ea0.png">

**Comment by olatechpro** [comment]
### Conclusion

From steve:

> Maybe it needs a checkbox:
> "Control Allowed Editors"
> If someone checks the box, then they see the field
