### ISSUE TITLE
Admin Menus and Yoast Premium menus

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#501]
These two premium menus are annoying in Yoast. They won't hide if you use Admin Menus:

<img width="347" alt="Screen Shot 2022-06-24 at 9 47 50 AM" src="https://user-images.githubusercontent.com/3868028/175550998-a44603d1-c433-4b13-8e69-a84b5de24c06.png">

**Comment by olatechpro** [comment]
Isn’t this duplicate of https://github.com/publishpress/PublishPress-Capabilities/issues/493? @stevejburge

**Comment by stevejburge** [comment]
@olatechpro doh! Sorry. Should have checked
