### ISSUE TITLE
Find all capabilities in wp_user_roles

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#506]
This user is reporting that our plugin does not find everything in wp_user_roles
https://wordpress.org/support/topic/it-was-easier-to-edit-the-wp-database/

**Comment by olatechpro** [comment]
@stevejburge we currently passed all wp_roles option capabilities. The user could be having any issue or related to not knowing the tab to find the capabilities to look for.

With the information provided, no way we can help or debug whatever the problem they are facing. I spent some time investigating the report and contrary to this issue, i can confirm we parse all roles capabilities.
