### ISSUE TITLE
Ability to block user login by role

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#510]
> I want to block a user's access. This is helpful. I will give you an example. Let's say a user has made use of posted something on the site for a while. Then he is no longer the manager, but everything he published as a post I want to keep, so I just deny him access, I can control user access to the platform

**Comment by agapetry** [comment]
@stevejburge I don't understand this feature request. It's already possible to demote a user to a lesser role. Doing so does not affect other users' access to that user's published posts.

**Comment by stevejburge** [comment]
One more request for this:

> We have a user that has written a lot of posts for the site, but now they are no longer employed with the company. We would like to keep their user account so as to continue attributing their writing to them. However, for security reasons, we would like to set it so that that user account can not log into the site at all, not even as a Subscriber. I have created a new role called Guest and have not given that role any capabilities at all. Is this sufficient to prevent a user account from logging in?

**Comment by olatechpro** [comment]
@stevejburge Are we adding a block/unblock member button to user profile field to implement this request or how do you want it to be?

**Comment by stevejburge** [comment]
@olatechpro What do you think? The alternative approach that occurred to me is creating a "Blocked" user role.

It could be part of this: https://github.com/publishpress/PublishPress-Capabilities/issues/182

**Comment by olatechpro** [comment]
@stevejburge what about adding "block role" option in roles screen settings?

That way, this feature will integrate with https://github.com/publishpress/PublishPress-Capabilities/issues/182 when finally implement and before then, the customer that need this feature can simply create a role, enable block option and add these users there?

**Comment by stevejburge** [comment]
That might be good approach, yes.

"Block users in this role for logging into the site."

**Comment by olatechpro** [comment]
Got it
