### ISSUE TITLE
Special treatment to hide "my template" from elementor [Bug]🐛

### ISSUE THREAD

**Issue by nreljed** [publishpress/PublishPress-Capabilities#523]
![Capture d’écran 2022-07-18 152215](https://user-images.githubusercontent.com/82481592/179535000-e6de341f-3342-4ff7-b36c-4bf7c7c9d633.png)

This is a detail that bothers me a lot and I can't figure out how to hide "my template" for the "editor" role which has the power to post.

despite the fact that I have ticked what I want this role to have the power to do and hidden the "my template" menu in admin menus

![Capture web_18-7-2022_152324_alpha test](https://user-images.githubusercontent.com/82481592/179534894-f7c2f23c-31c4-4734-8c86-9e8bd292a91e.jpeg)

![Capture d’écran 2022-07-18 152637](https://user-images.githubusercontent.com/82481592/179534940-b2a5c583-c65a-4e51-8289-3541bbffbc8e.png)

If anyone has an idea or has understood where the error is, please let me know.
there may be an instruction missing in the plugin code to force all other plugins to respect the parameters
elementor seems to ignore publishpress capabilities settings

**Comment by stevejburge** [comment]
Hi @nreljed 

This is possible with the Pro version of Capabilities which has the Admin Menus feature:
https://publishpress.com/knowledge-base/admin-menus/

**Comment by nreljed** [comment]
@stevejburge 
I speak to you with the pro version 2.4.3
I hope that tests will be done to confirm my bug
![Capture d’écran 2022-07-18 154023](https://user-images.githubusercontent.com/82481592/179536599-bce99b2a-58a4-4650-97a9-752b1cd9a879.png)

**Comment by stevejburge** [comment]
@nreljed Thanks. Please open a support ticket on PublishPress.com for Pro questions
