### ISSUE TITLE
It's possible to get lockout of admin menus when all items are checked

### ISSUE THREAD

**Issue by olatechpro** [publishpress/PublishPress-Capabilities#527]
Right now, we only prevent the menu from been removed but in case of where all menu are check, the unable to access this page is shown even though the admin is on admin menu screen `/wp-admin/admin.php?page=pp-capabilities-admin-menus&role=administrator
`
![lockout](https://user-images.githubusercontent.com/46832636/180443474-f196d19c-9b2d-4743-ac92-b8a7e34c2c41.jpg)

**Comment by olatechpro** [comment]
Pro PR https://github.com/publishpress/PublishPress-Capabilities/issues/527

**Comment by stevejburge** [comment]
Good catch, thanks @olatechpro
