### ISSUE TITLE
Control Custom Statuses option has a checkbox on 2 different screens

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#528]
Let's go with only the option in "Settings"
![Screen Shot 2022-07-26 at 9 32 46 AM](https://user-images.githubusercontent.com/3868028/181018667-664b3412-aba5-4b22-b0ba-affd37aa4e0f.png)
![Screen Shot 2022-07-26 at 9 32 40 AM](https://user-images.githubusercontent.com/3868028/181018672-78c7ffdb-a29d-47fa-87ec-f71259521a83.png)

**Comment by olatechpro** [comment]
Pro Pr https://github.com/publishpress/PublishPress-Capabilities-Pro/pull/150

**Comment by agapetry** [comment]
These checkboxes are tied to the same option storage.  Removing the checkbox from the Capabilities screen would make a key feature of the Pro edition (capability control for custom statuses) harder to discover.

**Comment by stevejburge** [comment]
@agapetry I do understand what you're saying here, but I also think we should focus on keeping settings in the "Settings" area. We'll be adding more, similar settings to this area soon.

**Comment by agapetry** [comment]
@stevejburge In that case, I think we need a welcome screen pointing out available settings to first-time users on plugin activation.

**Comment by stevejburge** [comment]
@agapetry With Custom Statuses, it's a bit a niche case? It requires at least one more plugin?
