### ISSUE TITLE
Additional Capabilities display is needed?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#541]
Do we need this on the user pages? It doesn't seem helpful and I've seen it confuse a couple of users

<img width="1233" alt="Screen Shot 2022-08-10 at 3 09 11 PM" src="https://user-images.githubusercontent.com/3868028/183998046-ecf8eaee-69a7-46a1-ad2f-6c2a7809e0b0.png">

**Comment by olatechpro** [comment]
@stevejburge That wasn't added by capabilities plugin

**Comment by stevejburge** [comment]
From Kevin:

"Ola is correct, that section is output by WordPress core: https://core.trac.wordpress.org/browser/trunk/src/wp-admin/user-edit.php#L867 "
