### ISSUE TITLE
Small text change when copying a role

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#548]
This line is confusing: "Contributor role copied to editor."

We can just say: "Contributor role copied."

<img width="418" alt="contrib-copy" src="https://user-images.githubusercontent.com/3868028/184428947-f8129ecd-be87-472c-9fce-5e7e628c89a2.png">

**Comment by olatechpro** [comment]
![copied](https://user-images.githubusercontent.com/46832636/185406858-7a01a119-3335-4f1c-b835-655e6d0cd484.jpg)

**Comment by stevejburge** [comment]
Thanks. The " to editor" part could be confusing there
