### ISSUE TITLE
Add disable WooCommerce admin restrictions in role settings

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#549]
This is confusing for our users:
https://publishpress.com/knowledge-base/wordpress-admin-area-access-for-woocommerce-users/

Can we make it easier?
https://woocommerce.com/document/allowing-customer-access-to-wp-admin-and-enabling-the-admin-bar/

**Comment by olatechpro** [comment]
@stevejburge how do you want this to be implemented and where should the settings be if we're adding a simple WooCommerce user access?

**Comment by stevejburge** [comment]
I wonder if it's possible to have a "Disable WooCommerce admin restrictions" setting inside individual Roles?

**Comment by olatechpro** [comment]
Okay, noted @stevejburge
