### ISSUE TITLE
Add a way for admins to test user accounts

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#57]
We should use add a feature like this so admins can test the accounts they create: https://wordpress.org/plugins/user-switching/

The text for the switcher can be "Test this user" instead of "Switch to"

![Screen Shot 2020-10-07 at 5 14 43 PM](https://user-images.githubusercontent.com/3868028/95388684-adf21a80-08c0-11eb-9adc-7b4a77467ac1.png)

Then the big message:
"You are testing as this user: Test. Click here to return to your Administrator view."

<img width="597" alt="Screen Shot 2020-10-07 at 5 15 31 PM" src="https://user-images.githubusercontent.com/3868028/95388721-bf3b2700-08c0-11eb-902b-d0dda2c56b04.png">

**Comment by agapetry** [comment]
@olatechpro  The front end switch back link still needs some work. Steve suggests styling it to match the Admin Bar.

**Comment by olatechpro** [comment]
Got it. Closing this for https://github.com/publishpress/PublishPress-Capabilities/issues/598
