### ISSUE TITLE
Add text description to Settings

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#573]
At the moment, our Capabilities settings don't have much information on what they do. Let's add some as we do in PublishPress Blocks

![Screen Shot 2022-09-12 at 13 57 06](https://user-images.githubusercontent.com/3868028/189734264-92ccff11-7b69-413f-9a27-23f907621419.png)

**Comment by olatechpro** [comment]
@stevejburge Can you suggest the description? My changes always need to go though changes and i feel we can just do it once.

**Comment by stevejburge** [comment]
<img width="566" alt="Screen Shot 2022-10-07 at 2 10 56 PM" src="https://user-images.githubusercontent.com/3868028/194622685-8c67208b-29e1-4a99-bcac-4981dc6104a1.png">

**Comment by stevejburge** [comment]
<img width="565" alt="Screen Shot 2022-10-07 at 2 12 18 PM" src="https://user-images.githubusercontent.com/3868028/194622741-b38563d7-8c5c-4b2f-a8ba-b7151589cb57.png">

**Comment by stevejburge** [comment]
<img width="571" alt="Screen Shot 2022-10-07 at 2 12 37 PM" src="https://user-images.githubusercontent.com/3868028/194622786-2af2e90e-f5a1-4a60-9a72-5284e49777cc.png">

**Comment by stevejburge** [comment]
<img width="728" alt="Screen Shot 2022-10-07 at 2 13 06 PM" src="https://user-images.githubusercontent.com/3868028/194622939-91c1fbee-b73b-4d6a-bb74-6c0369043534.png">
