### ISSUE TITLE
Multi-select JS fails to load on Profile Edit Screen

### ISSUE THREAD

**Issue by dotsam** [publishpress/PublishPress-Capabilities#576]
## Expected Behavior

Editing a user profile should present a multi-select `<select>` field augmented with `chosen.js`

## Current Behavior

A plain multi-select field is shown, and the following error is logged in the Javascript console:

```
[Warning] jQuery.Deferred exception: ppCapabilitiesProfileData.selected_roles.reverse is not a function. (In 'ppCapabilitiesProfileData.selected_roles.reverse()', 'ppCapabilitiesProfileData.selected_roles.reverse' is undefined) (2) (jquery.js, line 4050)
(anonymous function) — profile.js:35
mightThrow — jquery.js:3766
(anonymous function) — jquery.js:3834
undefined
```

## Possible Solution

The `$roles` array should be run through [array_values](https://www.php.net/manual/en/function.array-values.php) prior to localizing to ensure that it is contiguously indexed.
https://github.com/publishpress/PublishPress-Capabilities/blob/06ef8829a421b0d4fd8adc7e66e8d7c34198fe1d/includes/admin-load.php#L286

## Steps to Reproduce (for bugs)

The `$roles` prop of a `WP_User` is created by [filtering the user's capabilities and picking out caps that are actually/also roles](https://github.com/WordPress/WordPress/blob/30a13227bde8e217d695d1412e4116d1470afa70/wp-includes/class-wp-user.php#L512-L515):
```
		// Filter out caps that are not role names and assign to $this->roles.
		if ( is_array( $this->caps ) ) {
			$this->roles = array_filter( array_keys( $this->caps ), array( $wp_roles, 'is_role' ) );
		}
```

This can potentially lead to an array that is not contiguously indexed (ie. the first array element may have an index of `1` if the `0`th element of the `$caps` array was filtered out)

When it comes time to localize the admin JS https://github.com/publishpress/PublishPress-Capabilities/blob/06ef8829a421b0d4fd8adc7e66e8d7c34198fe1d/includes/admin-load.php#L286-L299

This non-associative array will ultimately be localized using `json_encode` which converts a non-contiguously indexed array to a JS object rather than a JS array, which the `profile.js` script is not expecting as it's trying to call a `Array.reverse()` method:

https://github.com/publishpress/PublishPress-Capabilities/blob/06ef8829a421b0d4fd8adc7e66e8d7c34198fe1d/common/js/profile.js#L35-L39

## Your Environment

* Version used: 4.5.0
* Browser Name and version: Safari 16.0
* Operating System and version (desktop or mobile): macOS 12.6
* Link to your project:

**Comment by stevejburge** [comment]
Thanks for such as detailed and helpful report, @dotsam

**Comment by dotsam** [comment]
I don't think the PR will actually resolve this issue for me, it's only being applied to the default roles, while the `$roles` property of the `WP_User` object returned for me is what isn't a continuously indexed array.

**Comment by stevejburge** [comment]
Thanks @dotsam

**Comment by olatechpro** [comment]
Hello @dotsam Is the reported issue caused by any capabilities features or implementation?

**Comment by olatechpro** [comment]
Hello @dotsam Is the reported issue caused by any capabilities features or implementation?

This will enable us to look at the code responsible for this issue and make correction

**Comment by dotsam** [comment]
Here's a more complete example to illustrate what's happening here.

Here is a dump of the WP_User object
<details><summary>WP_User</summary>
<p>

```php

WP_User::__set_state(array(
   'data' => 
  (object) array(
     'ID' => '27',
     'user_login' => 'USERNAME',
     'user_pass' => 'PASSWORDHASH',
     'user_nicename' => 'USERNAME',
     'user_email' => 'USEREMAIL',
     'user_url' => '',
     'user_registered' => '2014-01-07 01:28:17',
     'user_activation_key' => '',
     'user_status' => '0',
     'display_name' => 'USERNAME',
     'spam' => '0',
     'deleted' => '0',
  ),
   'ID' => 27,
   'caps' => 
  array (
    'wplc_ma_agent' => true,
    'editor' => true,
    'site_manager' => true,
    'wplc_cap_show_history' => true,
    'wplc_cap_show_offline' => true,
  ),
   'cap_key' => 'wp_36_capabilities',
   'roles' => 
  array (
    1 => 'editor',
    2 => 'site_manager',
  ),
   'allcaps' => 
  array (
    'moderate_comments' => true,
    'manage_categories' => true,
    'manage_links' => true,
    'upload_files' => true,
    'unfiltered_html' => true,
    'edit_posts' => true,
    'edit_others_posts' => true,
    'edit_published_posts' => true,
    'publish_posts' => true,
    'edit_pages' => true,
    'read' => true,
    'level_7' => true,
    'level_6' => true,
    'level_5' => true,
    'level_4' => true,
    'level_3' => true,
    'level_2' => true,
    'level_1' => true,
    'level_0' => true,
    'edit_others_pages' => true,
    'edit_published_pages' => true,
    'publish_pages' => true,
    'delete_pages' => true,
    'delete_others_pages' => true,
    'delete_published_pages' => true,
    'delete_posts' => true,
    'delete_others_posts' => true,
    'delete_published_posts' => true,
    'delete_private_posts' => true,
    'edit_private_posts' => true,
    'delete_private_pages' => true,
    'edit_private_pages' => true,
    'read_ai1ec_event' => true,
    'edit_ai1ec_event' => true,
    'edit_ai1ec_events' => true,
    'edit_others_ai1ec_events' => true,
    'edit_private_ai1ec_events' => true,
    'edit_published_ai1ec_events' => true,
    'delete_ai1ec_event' => true,
    'delete_ai1ec_events' => true,
    'delete_others_ai1ec_events' => true,
    'delete_published_ai1ec_events' => true,
    'delete_private_ai1ec_events' => true,
    'publish_ai1ec_events' => true,
    'manage_events_categories' => true,
    'manage_ai1ec_feeds' => true,
    'read_private_pages' => true,
    'read_private_posts' => true,
    'wp-piwik_stealth' => true,
    'read_private_aggregator-records' => true,
    'edit_aggregator-records' => true,
    'edit_others_aggregator-records' => true,
    'edit_private_aggregator-records' => true,
    'edit_published_aggregator-records' => true,
    'delete_aggregator-records' => true,
    'delete_others_aggregator-records' => true,
    'delete_private_aggregator-records' => true,
    'delete_published_aggregator-records' => true,
    'publish_aggregator-records' => true,
    'copy_posts' => true,
    'manage_local_site' => true,
    'wp-piwik_read_stats' => true,
    'wplc_ma_agent' => true,
    'editor' => true,
    'site_manager' => true,
    'wplc_cap_show_history' => true,
    'wplc_cap_show_offline' => true,
  ),
   'filter' => NULL,
   'site_id' => 36,
))
```

</p>
</details>

You can see that the `$caps` property (which is equivalent to the capabilities as stored in the database) contains `wplc_ma_agent`, `wplc_cap_show_history`, and `wplc_cap_show_offline`, but because they are not registered`WP_Role`s, they are filtered out of `$roles`, thus making `$roles` a non-zero-indexed array. 

This case may be somewhat unique in that the 1st listed role is actually a capability, when it should usually represent the user's "primary" role, but this same same situation could arise if a capability is inserted in the DB anywhere other than in the last index of the array, thus making it non-continuous and therefore translated to a JSON object rather than an array.

**Comment by olatechpro** [comment]
@dotsam I didn't say this is not possible to filter out roles by a custom action or have not contiguously indexed roles array.

However, what I'm asking for is the part of capabilities plugins that's responsible for this action so we can review it.

I believe if an external action or plugin or code perform this action, they should instead do a cleanup after.

**Comment by dotsam** [comment]
To the best of my knowledge, no other code is acting on the `$roles` property. Your own `getUsersRoles` method is getting the `WP_User` object and returning the roles:
https://github.com/publishpress/PublishPress-Capabilities/blob/d9b289519a182e8d4aadf35068c65f37f63dba52/includes/admin-load.php#L356-L369

And the raw properties of a `WP_User` object cannot be filtered elsewhere as far as I can see.

As I mentioned originally, it's the [get_role_caps](https://github.com/WordPress/WordPress/blob/30a13227bde8e217d695d1412e4116d1470afa70/wp-includes/class-wp-user.php#L502-L530) method in WordPress Core that is responsible for creating `$roles` from `$caps`:
```php
	/**
	 * Retrieves all of the capabilities of the user's roles, and merges them with
	 * individual user capabilities.
	 *
	 * All of the capabilities of the user's roles are merged with the user's individual
	 * capabilities. This means that the user can be denied specific capabilities that
	 * their role might have, but the user is specifically denied.
	 *
	 * @since 2.0.0
	 *
	 * @return bool[] Array of key/value pairs where keys represent a capability name
	 *                and boolean values represent whether the user has that capability.
	 */
	public function get_role_caps() {
		$switch_site = false;
		if ( is_multisite() && get_current_blog_id() != $this->site_id ) {
			$switch_site = true;

			switch_to_blog( $this->site_id );
		}

		$wp_roles = wp_roles();

		// Filter out caps that are not role names and assign to $this->roles.
		if ( is_array( $this->caps ) ) {
			$this->roles = array_filter( array_keys( $this->caps ), array( $wp_roles, 'is_role' ) );
		}

		// Build $allcaps from role caps, overlay user's $caps.
		$this->allcaps = array();
		foreach ( (array) $this->roles as $role ) {
			$the_role      = $wp_roles->get_role( $role );
			$this->allcaps = array_merge( (array) $this->allcaps, (array) $the_role->capabilities );
		}
		$this->allcaps = array_merge( (array) $this->allcaps, (array) $this->caps );

		if ( $switch_site ) {
			restore_current_blog();
		}

		return $this->allcaps;
	}
```

So I suppose one could make the argument that this is a problem in Core that should have a Trac ticket opened, but I also think you could be sanitizing this data for your specific needs too.

**Comment by olatechpro** [comment]
@dotsam 
> ....but I also think you could be sanitizing this data for your specific needs too.

That's the point, you mentioned it's causing problem with the multi select on new user screen and we already fix that by using the recommended array_values on the roles array.

That's why I'm asking where else this is affecting you in the capabilities plugin usage context to have a look at it.

**Comment by olatechpro** [comment]
Okay, i can see the misunderstanding, the `$roles = array_values($roles);` is currently at the wrong location. https://github.com/publishpress/PublishPress-Capabilities/blob/d9b289519a182e8d4aadf35068c65f37f63dba52/includes/admin-load.php#L305

It should be outside the `if (empty($roles)) { }`

That's exactly what I'm trying to understand with my question since that should have solve the problem.

@dotsam
