### ISSUE TITLE
Adding an explanation for Checkmark / empty / X

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#578]
A couple of times per week, I come across a user who isn't clear on the meaning of Checkmark / empty / X

"empty" is the confusing part. Some people think it means "allowed" and some think it means "denied".

I wonder if we need a small area in the sidebar explaining this? 

Or perhaps it could be a tooltip inside each box, similar to this:

<img width="539" alt="Screen Shot 2022-09-19 at 12 11 36 PM" src="https://user-images.githubusercontent.com/3868028/191063609-66972cd7-a781-458b-a371-2703ba2669a9.png">

**Comment by olatechpro** [comment]
....what should be the tooltips title for every state and i don't know if this should simply be input title or a real tooltips? @stevejburge

**Comment by stevejburge** [comment]
I'm thinking that a sidebar box maybe be best:

Check icon: This capability is granted.
Empty box: No change.
X icon: This capability is denied.

@agapetry Do those descriptions sound OK.

- We could also add a link to more detailed documentation.
- These boxes could appear on other screens such as "Admin Features"

**Comment by olatechpro** [comment]
@stevejburge @agapetry  
1. Can you confirm if this box should exist on other screen aside capabilities screen? Personally, I don't see the reasons it should be added to other screens other than the capabilities page
2. Do we have the documentation link already or i should skip that part till we have a link?

**Comment by stevejburge** [comment]
1. Yes, please. I think this will be useful for Admin Features and Editor Features too. On those screens, some people don't realize that we are can't grant extra access. So the box will look like this:

Empty box: No change.
X icon: This capability is denied.

We can also move text like this to the box: "Note: Capability changes remain in the database after plugin deactivation."

2. I'll create the documentation at https://publishpress.com/knowledge-base/checkboxes/

**Comment by olatechpro** [comment]
@stevejburge well, i was talking about capabilities explanation and thereby believe it doesn't apply for other screens but if that brings better understanding. Great then
