### ISSUE TITLE
Template panel is missing on Editor Features

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Capabilities#579]
As a user I want to be able to hide template panel from block editor: https://i.imgur.com/4gqeBuG.png

However, I don't find the option on Editor feature to hide it

**Comment by stevejburge** [comment]
@rizaardiyanto1412 Can you confirm this bug in your testing?

**Comment by rizaardiyanto1412** [comment]
@stevejburge Yes I do see it on my testing

**Comment by olatechpro** [comment]
Closing this for https://github.com/publishpress/PublishPress-Capabilities/issues/251
