### ISSUE TITLE
Some CPT is missing from Editor Features

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Capabilities#582]
ISSUE: If I have too many CPTs, some will be missing on editor features

Step to replicate:
1. Create 14 CPTs. 
2. Go to Editor features
3. Observe issue, you will miss some of your CPT
![image](https://user-images.githubusercontent.com/83811723/194080731-9031018d-af8e-48c7-8fca-50dd75cb6dac.png)

**Comment by olatechpro** [comment]
@stevejburge @agapetry I noticed this is as a result of the current implementation that require user to add `define('PP_CAPABILITIES_UNLIMITED_FEATURE_TYPES', true);` to their config.

So, should we inform customer to do so or this restriction needed to be removed?

**Comment by agapetry** [comment]
@olatechpro That limitation was implemented due to space limitations with the previous Editor Feature Restriction layout. It should be removed now that post types on that screen are listed with vertical tabs.

**Comment by olatechpro** [comment]
Noted @agapetry
