### ISSUE TITLE
Add a new WooCommerce permission

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#6]
User: 

> I installed the Capability Manager Enhanced plugin on a WooCommerce site in order to allow the "shop manager" user role to add new users. However, the "shop manager" can now add users -- but only with "customer" role. I need the shop manager to be able to add other "shop manager" users. Please advise.

Here's an explanation:
https://wordpress.org/support/topic/shop-manager-unable-to-edit-delete-users-with-certain-roles/
https://woocommerce.wordpress.com/2018/10/11/woocommerce-3-4-6-security-fix-release-notes/

**Comment by olatechpro** [comment]
### Closing it on this note:

To test, i added new user with shop manager role(and their only role) and in capabilities, i assign them “List user” and “Create User” role after which they’re able to add new users contrary to the issue description.

When i read the linked article, it talk about shop manager not been able to edit user in other role which is contrary to the issue description and according to the woocommerce article and comment [here](https://wordpress.org/support/topic/shop-manager-unable-to-edit-delete-users-with-certain-roles/).
They prevent shop manager by default from editing users with certain role and not from adding user and added a filter to add to list of role shop manager could be allowed to edit and i believe that fix the customer problem or whoever want shop manager to be able to edit specific roles but i’m not sure if we really need to add this code to define specific role shop manager could edit :thinking_face:.
