### ISSUE TITLE
Test User text

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#608]
1. Let make this the final tab

2. "When testing, display a caption in the admin bar and a return link in the login popup."  What is the login popup?

3. "When testing, display a return link in the front end footer."

<img width="917" alt="Screen Shot 2022-10-20 at 9 24 47 AM" src="https://user-images.githubusercontent.com/3868028/196960955-c760bad6-f653-4a0e-a985-f42ea5fcda59.png">

**Comment by agapetry** [comment]
> What is the login popup?

@stevejburge  I mentioned "popup" to suggest why no return link is immediately visible. I guess we can skip that hint if there's no universally recognized standard term for the box that appears when you hover over (or in mobile, click on) the upper right corner of the Admin Bar:

"When testing, display a caption and return link in the Admin Bar."

**Comment by stevejburge** [comment]
@agapetry Yes, that short version sounds good
