### ISSUE TITLE
Usage Key for Admin Menus and Nav Menus

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#610]
Let's add these boxes for Admin Menus and Nav Menus too, please:
<img width="1071" alt="Screen Shot 2022-10-21 at 1 00 54 PM" src="https://user-images.githubusercontent.com/3868028/197249952-a41892cc-ffde-4c0c-96c2-02bb7b1b48d4.png">

**Comment by olatechpro** [comment]
Fixed in pro
