### ISSUE TITLE
Editor feature not working on Product (Woocommerce)

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Capabilities#625]
Ticket: 
https://secure.helpscout.net/conversation/2051845756/170333?folderId=2557461
https://secure.helpscout.net/conversation/2042609588/169927?folderId=2557461

Step to replicate:
0. Make sure to have Woocommerce installed
1. Go to Capabilities > Editor Feature
2. Select Product post type
3. Try hide some metabox (e.g. Publish box)
4. Login to that user 
5. Create new product, observe that the metabox that we hide on step 3 are not hidden for that role

Editor feature works fine on page & post

**Comment by olatechpro** [comment]
@rizaardiyanto1412 I just tested this feature and it's working.

Can you make video for me to see to check how you're doing it?

**Comment by rizaardiyanto1412** [comment]
Strange, I'm not able to replicate it either. I believe I was able to replicate this issue before, but now it's fine. 

Let me confirm with customer first @olatechpro and if they confirmed working fine, we can close this

**Comment by rizaardiyanto1412** [comment]
@olatechpro The user confirmed the issue does not there anymore. We can close this one. Thanks Ola
