### ISSUE TITLE
Drag and drop ability on custom item

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Capabilities#632]
On custom item (Custom CSS or block URL), it will be great if we can sort them and drag and drop the item

> This will allow us to avoid constantly deleting and redoing the CSS,
> because each time we cannot target or find the exact CSS, so we have to test several times and delete several times, not to mention that if we have 10 custom items, it is impossible to edit them or organize them according to our structured order

![image](https://user-images.githubusercontent.com/83811723/205231531-0e3c80b2-45e5-4dd4-8484-536332af2e1c.png)

Original thread: https://wordpress.org/support/topic/import-custom-items-edit-and-order/

**Comment by stevejburge** [comment]
This is not a bad idea. We can improve the UI here

**Comment by olatechpro** [comment]
Drag and drop is only possible when we have all items in a single row like Profile features.

However, we're adding the edit feature in https://github.com/publishpress/PublishPress-Capabilities/issues/741 and that'll do solve the issue of having to delete and readd
