### ISSUE TITLE
Change "PublishPress" to "PublishPress Planner"

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Capabilities#638]
![image](https://user-images.githubusercontent.com/83811723/205917745-7fc81350-422f-4b95-a12e-87638ed13c29.png)

Change the name to "PublishPress Planner"

**Comment by rizaardiyanto1412** [comment]
@stevejburge Can this go to 2.6.1 milestone?

**Comment by stevejburge** [comment]
@rizaardiyanto1412 sure thing
