### ISSUE TITLE
Solid borders for all columns

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#643]
There's a few areas where we aren't consistent across screens. 

Here's one: Admin Menus has a table border: <img width="1028" alt="Screen Shot 2022-12-08 at 10 33 18 AM" src="https://user-images.githubusercontent.com/3868028/206488090-b35ff6f8-970e-4e4b-810f-adbef58eb072.png">

Admin Menus features does not:
<img width="1030" alt="Screen Shot 2022-12-08 at 10 33 28 AM" src="https://user-images.githubusercontent.com/3868028/206488098-1bfa21dd-cc6e-4777-ab5d-aea445bb3231.png">

**Comment by olatechpro** [comment]
@stevejburge Here's how the screen looks to me:

Admin features
![admin-features](https://user-images.githubusercontent.com/46832636/214317559-8f972cb0-6f5b-4ac6-989f-64929250ef28.jpg)

Admin Menus
![admin-menus](https://user-images.githubusercontent.com/46832636/214317592-13ff16d3-035d-4a86-b266-a65cad0f9d26.jpg)

Nav Menus
![nav-menus](https://user-images.githubusercontent.com/46832636/214317630-5a7e817c-aa9a-4e76-a86a-e9f164d96595.jpg)

Editor Features
![editor-features](https://user-images.githubusercontent.com/46832636/214317792-d2784074-5579-45b9-a56e-34f4676835af.jpg)

Judging from the above 4 screenshots, which border are you referring to that's not consistent or if the screenshots aren't like above, maybe this issue should be delayed till you have update for confirmation or maybe provide more details?

**Comment by stevejburge** [comment]
OK, thanks @olatechpro It's very helpful to see those screenshots lined up like that.

It looks like Admin Menus is now consistent with the others.
