### ISSUE TITLE
Use tabs for "Admin Features"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#644]
Would it make sense to use a tabbed view for "Admin Features"?

Header and Footer 
Dashboard widgets 
Hide CSS Element 
Blocked by URL 

This would more closely match the other key screens in Capabilities and also make it easier to navigate.

**Comment by olatechpro** [comment]
@stevejburge Horizontal or Vertical tab?

**Comment by stevejburge** [comment]
@olatechpro Vertical. I had been thinking of consistent design with the Capabilities and Editor Features screens.

But maybe we should be consistent with the Profile Features / Admin Menus / Nav Menus screens instead
