### ISSUE TITLE
PHP 8 Deprecation Error

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Capabilities#651]
It’s an error with a vendor package and we can’t upgrade to their latest version due to our support for lower php version (5.6 for example)

https://plugintests.com/plugins/wporg/capability-manager-enhanced/latest

original thread; https://wordpress.org/support/topic/php-8-deprecation-errors-3/

**Comment by stevejburge** [comment]
This will be solved by the removal of PHP 5.6 support in March

**Comment by bastienuh** [comment]
Hi, it seems the error is still present. I have just installed the plugin and I still have the deprecation errors.
Do you plan to solve it quickly? If I use the pro version, is the bug there too?

Thanks for you answers.
<img width="896" alt="Capture d’écran 2023-04-28 à 17 42 49" src="https://user-images.githubusercontent.com/1685778/235193110-4d4bbc1d-8d7d-4535-ade0-10a00b8b379c.png">

**Comment by BlackWireKevin** [comment]
It would be great to see this get fixed. This writes thousands of lines of debug errors and its been months since others have brought it up.

**Comment by stevejburge** [comment]
@BlackWireKevin We're working in this. We rebuilding how we store libraries such as Pimple, so that the plugin is more friendly to tools such as Composer, Docker, and Bedrock. We hope to complete this for all our plugins by the end of August.
