### ISSUE TITLE
Should we add "Toggle All" to Admin Features

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#656]
We have Toggle All on this screen and others: 

<img width="484" alt="Screen Shot 2023-01-13 at 11 22 44 AM" src="https://user-images.githubusercontent.com/3868028/212369028-cfcf1e4b-9f58-47f4-8a34-c57f0b5d35ce.png">

But not Admin Features:
<img width="545" alt="Screen Shot 2023-01-13 at 11 24 12 AM" src="https://user-images.githubusercontent.com/3868028/212369414-2743ec96-fc38-41d2-afbf-38512ce5acbc.png">

**Comment by olatechpro** [comment]
This has been implemented now
