### ISSUE TITLE
Type-Specific Capabilities showing options that don't work

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#71]
I see this with new install of Capabilities:
<img width="265" alt="Screen Shot 2020-10-02 at 1 07 20 PM" src="https://user-images.githubusercontent.com/3868028/94950229-47c85a80-04b0-11eb-99e1-b39bd0296e79.png">

But only Changesets appears with checkboxes. Related: do we need a better word than "Changesets"?
<img width="806" alt="Screen Shot 2020-10-02 at 1 07 59 PM" src="https://user-images.githubusercontent.com/3868028/94950273-60387500-04b0-11eb-8553-c7fad3d51f93.png">

**Comment by agapetry** [comment]
@stevejburge Where are those post type registrations coming from?

**Comment by stevejburge** [comment]
@agapetry I'm seeing this on 100% fresh installs

**Comment by agapetry** [comment]
Okay, those are non-public post types defined by WordPress.  We shouldn't expose them as options for type-specific permissions, at least not until after reviewing the implications for each one.  I'll prepare a minor release to suppress those for now.
