### ISSUE TITLE
Nav Menus Block Navigation/FSE theme support

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#710]
It seems like Nav Menus picks up the old style of menus but not those in Full Site Editing

These are menus here: /wp-admin/edit.php?post_type=wp_navigation

They are created with the Navigation Block
<img width="662" alt="Screenshot 2023-02-27 at 8 18 16 AM" src="https://user-images.githubusercontent.com/3868028/221574145-c69b8088-487e-4d5a-ada9-9cd5c4962886.png">

**Comment by stevejburge** [comment]
Thanks @olatechpro. Yes, this does get tricky. However, I guess it's also an opportunity for our plugin to stand out.

Am I right in thinking that the new FSE menus are stored in a post type?

**Comment by agapetry** [comment]
@olatechpro The approach you describe is also what I would recommend.

**Comment by agapetry** [comment]
@olatechpro I ran into some notices after adding a navigation block to my front page: 
![image](https://user-images.githubusercontent.com/43488774/230474924-0d1fd37f-2a13-4e3a-99fc-7c6b08571918.png)

**Comment by agapetry** [comment]
However, I confirmed that the active restrictions are applied to either FSE or conventional nav menus (whichever are active for the theme).
