### ISSUE TITLE
Add multisite capabilities tab

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Capabilities#737]
Based on discussions with @stevejburge on a fresh multisite installation, there is no additional capabilities
![image](https://user-images.githubusercontent.com/83811723/225283562-3ead4ee8-5c67-4603-bc9d-fe40fd0ab39c.png)

While it should be a lot of them
![image](https://user-images.githubusercontent.com/83811723/225283618-68434bb0-7301-437a-b00f-514a827c6fa2.png)

Reference: https://wordpress.org/documentation/article/roles-and-capabilities/

**Comment by olatechpro** [comment]
@rizaardiyanto1412 @stevejburge The capabilities is not showing because it's not on the capabilities list by default.

You can test by adding for example 'manage_network' and it'll show in additional settings.

**Comment by stevejburge** [comment]
Thanks @olatechpro 

Is there a way we load these automatically for multisites?
