### ISSUE TITLE
Profile Features table safari styles fix

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#770]
<img width="894" alt="Screenshot 2023-04-17 at 8 16 34 AM" src="https://user-images.githubusercontent.com/3868028/232481574-0b5bbe84-6d12-46b5-b398-eb6349039da7.png">

**Comment by stevejburge** [comment]
Seems to be the same with elements also:
<img width="1060" alt="Screenshot 2023-04-19 at 10 36 11 AM" src="https://user-images.githubusercontent.com/3868028/233109836-a98936be-15fa-4b79-b325-5e32b638c667.png">

**Comment by olatechpro** [comment]
@stevejburge I can't see this issue on both firefox and chrome.

Can you give more information on the browser details?
