### ISSUE TITLE
Fatal PHP error following composer update (Capabilities Pro)

### ISSUE THREAD

**Issue by templeman** [publishpress/PublishPress-Capabilities#795]
**I'm leaving this here in the PublishPress-Capabilities repo, but I'm actually using the 'Pro' version of the plugin.** At first glance it looks like a possible mismatch in Composer dependencies causing a fatal PHP error.

## Expected Behavior

Upon running `composer update` with a composer-installed version of PublishPress Capabilities Pro, I should be able to access the WP admin as usual.

## Current Behavior

After recently running `composer update`, I can no longer access the WP admin. Instead I get an HTTP 500 error.

## Possible Solution

In php `debug.log` I see the following error

```
[28-Apr-2023 17:45:07 UTC] PHP Fatal error:  Uncaught Error: Class "PublishPress\Pimple\Container" not found in /srv/www/example.com/current/vendor/alledia/wordpress-edd-license-integration/src/core/Container.php:38
Stack trace:
#0 /srv/www/example.com/current/vendor/composer/ClassLoader.php(582): include()
#1 /srv/www/example.com/current/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}('/srv/www/modern...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('PublishPress\\ED...')
#3 /srv/www/example.com/current/web/app/plugins/capabilities-pro/includes-pro/library/Services.php(52): class_exists('\\PublishPress\\E...')
#4 /srv/www/example.com/current/web/app/plugins/capabilities-pro/includes-pro/library/Factory.php(30): require_once('/srv/www/modern...')
#5 /srv/www/example.com/current/web/app/plugins/capabilities-pro/includes-pro/admin-load.php(230): PublishPress\Capabilities\Factory::get_container()
#6 /srv/www/example.com/current/web/wp/wp-includes/class-wp-hook.php(308): PublishPress\Capabilities\AdminFiltersPro->loadUpdater('')
#7 /srv/www/example.com/current/web/wp/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#8 /srv/www/example.com/current/web/wp/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#9 /srv/www/example.com/current/web/wp/wp-admin/admin.php(175): do_action('admin_init')
#10 /srv/www/example.com/current/web/wp/wp-admin/index.php(10): require_once('/srv/www/modern...')
#11 {main}
  thrown in /srv/www/example.com/current/vendor/alledia/wordpress-edd-license-integration/src/core/Container.php on line 38
```

Additionally, composer also throws the following:
```
Package alledia/wordpress-edd-license-integration is abandoned, you should avoid using it. Use publishpress/wordpress-edd-license instead.
Package publishpress/publishpress-instance-protection is abandoned, you should avoid using it. Use publishpress/instance-protection instead.
```

Looks like some dependencies changed or were renamed, but perhaps Capabilities Pro hasn't been updated to reflect this?

## Steps to Reproduce (for bugs)

1. Install the latest PublishPress Capabilities Pro (2.7.1) via Composer (in my case the repo is added at my https://packagist.com account, and composer fetches it from there)
2. Attempt to visit the wp dashboard, which fails to load.
Uninstalling and re-installing the plugin via composer commands yields the same result.
I've also tried downgrading to the prior version (2.7.0) with the same result.

## Context

I've had the Pro version of the Capabilities plugin installed for months without issue. Yesterday I ran a `composer install && composer update` command and this issue appeared.

## Your Environment

* Version used: 2.7.1 (Pro). Same result downgrading to 2.7.0 (Pro)
* PHP: 8.0

**Comment by andergmartins** [comment]
Hi @templeman thanks for reporting that.

We were updating some libraries and pushed some changes to those repos by mistake.
Please, could you try running `composer update` again? You still will see the warning about those two abandoned packages, but you can ignore that for now. That will be fixed soon on a new release of Capabilities Pro.

You might see `alledia/wordpress-edd-license-integration` at version 2.3.8 and `publishpress/publishpress-instance-protection` at version 1.0.3.

**Comment by templeman** [comment]
@andergmartins Thanks for the quick fix! I can confirm that the error is gone now after running `composer update`.

**Comment by andergmartins** [comment]
Awesome, thank you for the feedback and help on this one 🙏🏻
