### ISSUE TITLE
Remove Show Classic Editor Controls on Editor Features screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#797]
Do we need this if users don't have the Classic Editor plugin?

<img width="457" alt="Screenshot 2023-05-03 at 8 38 36 AM" src="https://user-images.githubusercontent.com/3868028/235918307-f08ed717-174e-40f7-a362-2985c1b349fa.png">

**Comment by olatechpro** [comment]
@stevejburge I can't really remember very well the primary reason we added the button but I'm sure it's related to not been able to detect all cases where plugins or themes uses classic editor without classic editor plugin.

So, it's there for that reason or issue.

**Comment by stevejburge** [comment]
OK, thanks.

Could this be solved with this "Settings" area?


![Screenshot 2023-05-03 at 10 51 39 AM](https://user-images.githubusercontent.com/3868028/235953366-66ae3cc7-03a9-4d8d-94df-ec6fdf04caac.png)

**Comment by olatechpro** [comment]
Yes, we have it in settings area as well. @stevejburge

**Comment by stevejburge** [comment]
Thanks. I think that's enough. Can we remove the button on the main screen?

**Comment by olatechpro** [comment]
Okay
