### ISSUE TITLE
Add frontend features documentation link

### ISSUE THREAD

**Issue by olatechpro** [publishpress/PublishPress-Capabilities#799]
We have a custom link for all features documentation like https://publishpress.com/knowledge-base/editor-features/ for editor features, we need similar link for frontend feature when it's out to https://publishpress.com/knowledge-base/frontend-features/

**Comment by olatechpro** [comment]
@stevejburge This is for you, not sure if it's been done already ad we only need to update the link?

**Comment by stevejburge** [comment]
@olatechpro Yes, we can close this
