### ISSUE TITLE
Language filename and translation confusion issue

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Capabilities#800]
Hi, @andergmartins @stevejburge ,

This morning I found that in my local site the folder of PublishPress Capabilities is labelled by WP as capability-manager-enhanced and so it is named the file on the online system.

When I checked online plugin situation this morning there were 32 strings untranslated for Italian (I did it) and Spanish was 100% translated while French still has 53 untranslated strings.

Where's the issue? Files inside your code are pointing to "capsman-enhanced" files located inside the plugin language folder. There'll be no problems if the strings online are not different in quantity and ID location.

So said, I then opened the local capsman-enhanced file and in Italian there were 50 strings untranslated, 60 in Spanish and 51 in French.

- My suggestion is "can you rename the inside file name from "capsman-enhanced" to the same name of the folder to match the online denomination to avoid confusion?

- My solution at present is:

1.     I made the translation of "capsman-enhanced-it_IT.po" comparing with the translation of "capability-manager-enhanced-it_IT.po" so to match the two translation

2.     I can download the Spanish made by another and make the translation of "capsman-enhanced-es_ES.po" matching the online translation descriptions.

3. I make the French translation of "capsman-enhanced-fr_FR.po" then upload online and make the translation of the still untranslated strings online.

Please, let me know how to proceed.

Thanks
Angelo

**Comment by wocmultimedia** [comment]
I updated the present local files of "capsman-enhanced" of ES-FR-IT that you find below and please, add to plugin's languages folder
[CapablitiesFree-ES-FR-IT_Translation_Updates_May2023.zip](https://github.com/publishpress/PublishPress-Capabilities/files/11406203/CapablitiesFree-ES-FR-IT_Translation_Updates_May2023.zip)

Any inconvenient contact me
Thanks
Angelo

**Comment by olatechpro** [comment]
@stevejburge @agapetry  I'll suggest we delay this till PublishPress Statuses update as this will be hard for @agapetry to merge as almost all the plugins files will have new changes due to changing localisation domain for every files.

**Comment by stevejburge** [comment]
@olatechpro I've made a new milestone for the Statuses integration
