### ISSUE TITLE
Full Site Editing menus bug with custom link

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#807]
I can confirm this bug report:
https://secure.helpscout.net/conversation/2237613560/186056?folderId=2557464

If you have two menus, the last item on the top menu is controlling the second menu. In this screenshot, "bbc.com" is controlling the "Header navigation"
<img width="539" alt="Screenshot 2023-05-10 at 12 35 52 PM" src="https://github.com/publishpress/PublishPress-Capabilities/assets/3868028/cd5449c8-c3e2-45b0-a735-55b3b20952d0">

**Comment by olatechpro** [comment]
### Developer Note
Note: This happen because custom link menu item has same value as we're currently using ID, Block Name and Oject ID to generate slug where and in this case, all custom links has 0 as ID, core/navigation-link as block name and custom_block as Object ID.

So, that need to change
