### ISSUE TITLE
Make it easier to distinguish taxonomies

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#809]
One user wants some clarity for taxonomies. It could be a post type name? Perhaps the taxonomy slug?

This could be optional, perhaps disabled by default

> I was looking to customize some Role Capabilities in PublishPress Capabilities Pro and noticed that there's a lot of vague post types (and taxonomies) because various third-party plugins often add their own object types which might share the same names.
> 
> In this screen capture, multiple plugins provide their own custom post types to create custom post types and taxonomies (ACF and ACF Extended). There's also Ninja Forms which provides Submissions (and not to be confused with Forms which belongs to ACF Extended). Then there's the Notifications which comes from another of your plugins but could be confused for something related to Forms and Submissions (terms Gravity Forms uses, for example).
> 
> It would be helpful if the post type labels included the post type name as a suffix or separate column. In ACF, which has a number of locations where you filter by post type or taxonomy, they add the object type's name in parenthesis after the object type's label ("Category (my_category)").

![OD2t18b](https://github.com/publishpress/PublishPress-Capabilities/assets/3868028/74829099-9797-4268-b1eb-2b972604b050)

**Comment by olatechpro** [comment]
@stevejburge 
This is like Capabilities issue, no way to know which plugin added a post type or taxonomies unless we add feature like Capability Extractor we're currently building.

Maybe a subsection for Taxonomies and Post Types?

**Comment by stevejburge** [comment]
@olatechpro Let's show the slug in the tooltip for now.

"The slug for this taxonomy is ..."
"The slug for this post type is ..."
