### ISSUE TITLE
Move items from Roles Column to the Roles screen.

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#817]
Do we keep adding new columns? Is there a better approach to this screen?

<img width="1402" alt="Screenshot 2023-05-11 at 9 31 10 AM" src="https://github.com/publishpress/PublishPress-Capabilities/assets/3868028/0d597809-9e8d-45ca-9f49-800682a4a086">

**Comment by stevejburge** [comment]
@olatechpro Let's move this to the next Feature milestone.

One approach will be to show items from inside the "Roles" screen.

- Dashboard Access
- Login Redirect

I'll keep looking for more ideas. Maybe we can expand on the settings inside the "Roles" screen.

**Comment by olatechpro** [comment]
@stevejburge We currently doesn't have any of the mentioned item on the roles table. So, what are you talking about or what item are we moving to
Dashboard Access
Login Redirect?

**Comment by stevejburge** [comment]
@olatechpro My thinking here is that the "Roles" screen could show some settings from inside "Roles"

I'm not sure the current columns are helpful, except for the "Users" column.

**Comment by stevejburge** [comment]
@olatechpro Sure thing. The sidebar makes sense to me for the counts

**Comment by olatechpro** [comment]
@stevejburge Sorry, are we moving every column from Users, Capabilities to Nav menus or we're leaving some column?

**Comment by stevejburge** [comment]
So this is my attempt to improve this screen. Some column suggestions:

- Users: This is unchanged
- Role Type: "WordPress Core" or "Custom"
- Default Role: Check icon for the default role
- Admin Access: Check icon if users can access the admin area (can we detect this accurately?)

**Comment by olatechpro** [comment]
@stevejburge 
1. Do you mean all these columns moves to the role screen and removed from column except Users column?
<img width="1402" alt="237704586-0d597809-9e8d-45ca-9f49-800682a4a086" src="https://github.com/publishpress/PublishPress-Capabilities/assets/46832636/ceac8e69-53dc-46da-b46b-baa3b6947b24">

2. `Admin Access: Check icon if users can access the admin area (can we detect this accurately?)`
What other way to do you have on mind to detect that other than capability check for read? Asking cos of your question

**Comment by stevejburge** [comment]
1. Yes, I'm suggesting removing the existing columns except "Users"
2. That's what I'm wondering. Can we detect problems such as WooCommerce admin restriction?

**Comment by olatechpro** [comment]
It's still capability check and can only factor know capabilities. No general way to detect unknown restriction.
When woocommerce plugin is active, we'll look for `view_admin_dashboard` and when not, we'll look for `read` capability.

No automatic way unless we know plugins that restrict access and the needed capabilities incase any restrict access like woocommerce @stevejburge

**Comment by stevejburge** [comment]
@olatechpro WooCommerce is perhaps the only plugin I know that does this.

Could we check for "read" and then also "view_admin_dashboard" if we detect WooCommerce?

**Comment by olatechpro** [comment]
Yea, will do that @stevejburge
