### ISSUE TITLE
Update dashboard feature texts

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#820]
The dashboard looks quite empty.

Can we add the full text from here? https://github.com/publishpress/PublishPress-Capabilities/issues/491#issuecomment-1488867023 

Maybe we tighten up the spacing too?
Maybe there's a link to the feature if it is enabled?

<img width="1126" alt="new-dashboard" src="https://github.com/publishpress/PublishPress-Capabilities/assets/3868028/d8af1240-fd63-464c-a5fb-145a2860de19">

**Comment by olatechpro** [comment]
@stevejburge I think @agapetry updated the text from the ones in https://github.com/publishpress/PublishPress-Capabilities/issues/491#issuecomment-1488867023

Maybe you should talk to him first?

**Comment by stevejburge** [comment]
@olatechpro Let's go with the longer text, please

That will reduce the empty space
