### ISSUE TITLE
Select "Load on page types" by default

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#838]
Let's select this by default so it's one less thing for users:
<img width="735" alt="Screenshot 2023-05-22 at 3 27 18 PM" src="https://github.com/publishpress/PublishPress-Capabilities/assets/3868028/90c042d5-6bf6-4f30-89ed-a90bb84e9d99">

From @agapetry 

> What is the intended meaning of saving the entry with "Load on page types" blank?  If this selection is required for functionality, it should also be required to save the entry (red asterisk, etc.)
> If there is not an implicit "apply everywhere" behavior, I agree "Whole Site" should be selected by default
>

**Comment by olatechpro** [comment]
Load styles on whole site" is a checkbox. Enabled by default
If you uncheck it, those other options appear

![Screenshot 2023-06-23 at 11 30 39 AM](https://github.com/publishpress/PublishPress-Capabilities/assets/46832636/ae6517d2-2944-4202-953a-cc2a4865c292)"
