### ISSUE TITLE
Don't show "Add post metabox:" for "Custom Styles

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#840]
<img width="1005" alt="Screenshot 2023-05-22 at 3 29 35 PM" src="https://github.com/publishpress/PublishPress-Capabilities/assets/3868028/7fbe7a27-5318-4b4a-a1c2-2b7006d8392b">

**Comment by olatechpro** [comment]
Since we'll merging "Custom Styles" and "Frontend Elements" per https://github.com/publishpress/PublishPress-Capabilities/issues/837, I believe this requirement is no longer valid @stevejburge?

**Comment by stevejburge** [comment]
@olatechpro Yes, we can close this
