### ISSUE TITLE
Fatal error on plugin activation

### ISSUE THREAD

**Issue by anhackin** [publishpress/PublishPress-Capabilities#846]
Hello,

I have the following error when I try to activate the plugin:

Fatal error: Uncaught Error: Call to undefined function pp_capabilities_sub_menu_lists() in /srv/web/apps/wp-content/elementor/plugins/capability-manager-enhanced/includes/manager.php:341 Stack trace: #0 /srv/web/apps/wordpress/core/6.1.1/wp-includes/class-wp-hook.php(308): CapabilityManager->cme_menu() #1 /srv/web/apps/wordpress/core/6.1.1/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #2 /srv/web/apps/wordpress/core/6.1.1/wp-includes/plugin.php(517): WP_Hook->do_action() #3 /srv/web/apps/wordpress/core/6.1.1/wp-admin/includes/menu.php(155): do_action() #4 /srv/web/apps/wordpress/core/6.1.1/wp-admin/menu.php(420): require_once('...') #5 /srv/web/apps/wordpress/core/6.1.1/wp-admin/admin.php(158): require('...') #6 /srv/web/apps/wordpress/core/6.1.1/wp-admin/plugins.php(10): require_once('...') #7 {main} thrown in /srv/web/apps/wp-content/elementor/plugins/capability-manager-enhanced/includes/manager.php on line 341

**Comment by stevejburge** [comment]
Hi @anhackin 

It looks like the plugin is installed in a very unusual folder: /elementor/plugins/

Any reason why it's not in /wp-content/plugins?

**Comment by anhackin** [comment]
Hi @stevejburge 

Thank you for your answer. Yes you are right, the "wp-content" folder is on an unusual location because we run a WordPress farm (multiple website on the same instance).

The wp-config.php define these constants in order to move the folders to the right locations: 

WP_CONTENT_DIR  // no trailing slash, full paths only
WP_CONTENT_URL  // full url 
WP_PLUGIN_DIR  // full path, no trailing slash
WP_PLUGIN_URL  // full url, no trailing slash

Documentation about these constants can be found here: https://codex.wordpress.org/Determining_Plugin_and_Content_Directories#Constants

The WordPress core application is stored here: /srv/web/apps/wordpress/core/<version>
The WordPress wp-content folder is stored here: /srv/web/apps/wp-content/<website_identifier>
The WordPress plugin folder is stored here: /srv/web/apps/wp-content/<website_identifier>/plugins

I never had any issues before with that configuration, I just subscribed to the premium version of the plugin in this morning and after the installation I was unable to activate it. 

I guess it's maybe missing in the implementation ?

**Comment by stevejburge** [comment]
Thanks @anhackin 

It's possible. We're building solutions at the moment for non-traditional setups, for example with Composer.

Could you share more details on your tech stack, including your PHP?

**Comment by andergmartins** [comment]
@anhackin in addition to that, please could you check if the file `/srv/web/apps/wp-content/elementor/plugins/capability-manager-enhanced/includes/functions-admin.php` exists on your installation? 

That is the file that defines the missed function `pp_capabilities_sub_menu_lists`, and it uses only the relative path for the current file:

https://github.com/publishpress/PublishPress-Capabilities/blob/development/capsman-enhanced.php#L135

No constant, or hardcoded path is being used there.

**Comment by anhackin** [comment]
Thanks you both for your answers. It was indeed the missing file.

Sorry for inconvenience, I should have check that before.
I just did the installation again and it worked.
