### ISSUE TITLE
Part of the plugin still run even if invalid PHP version is found

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Capabilities#847]
## Expected Behavior

If a user is using PHP 5.4 or below, we display an admin warning saying that version is not compatible and avoid loading the plugin.

## Current Behavior

It displays the warning but there are a few hooks that are still added, even when the invalid PHP version is identified:

https://github.com/publishpress/PublishPress-Capabilities/blob/v2.8.1/capsman-enhanced.php#L148-L163

Not all the code is prevented to be executed on that case.

## Possible Solution

Move the highlighted code into the `else` block on the version compare check, so we only execute that code if a compatible PHP version is found.

**Comment by olatechpro** [comment]
Thanks @andergmartins This has been fixed
