### ISSUE TITLE
Permissions for blocks

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#85]
It would awesome to have the ability to choose which roles can see a block on the frontend of the site

This could be a select list with "All user roles" selected by default
![Screen Shot 2020-10-22 at 9 35 56 AM](https://user-images.githubusercontent.com/3868028/96879449-0fca8c80-144a-11eb-8041-95c9b6ae9cb1.png)

**Comment by olatechpro** [comment]
That's great but will this be limited to page alone ?

**Comment by stevejburge** [comment]
thanks @olatechpro. Can you explain that more?

**Comment by olatechpro** [comment]
Basically, user can add any item to menu which could be Page, Post, custom post, categories. 

So, i'm asking if we decided to give a custom block while creating item(page for example ), ate we extending this custom block to only page, or post or custom post type edit screen as well?

Not sure if it's clear enough now?

**Comment by stevejburge** [comment]
Great questions as always.

For the first version, my thinking is that this  setting will apply everywhere this block is shown.

This setting will apply to any block (Image, Paragraph, Heading etc), it doesn't have to be a custom block.

**Comment by olatechpro** [comment]
Not sure you understand me very well yet.
Do you know different wordpress post type have different post area? 

-When creating a page
-When creating a post
-When creating category
-When creating 'Any custom post type'

Etc. 


All the mentioned wordpress post type have different creation area. 

So, i'm asking if we'll be adding this custom block to page alone (when creating page) or extend it to others like post(when creating post) etc so they can select who have permission to this post, page or custom post when creating them

**Comment by olatechpro** [comment]
Okay, i think i misunderstood you before by thinking you mean post meta.

So, all clear now 😂

**Comment by stevejburge** [comment]
Thanks @olatechpro. Maybe this screenshot helps?
<img width="693" alt="Screen Shot 2020-10-22 at 3 18 43 PM" src="https://user-images.githubusercontent.com/3868028/96919565-f2adb200-1479-11eb-8ac7-3c364ba11ce1.png">

**Comment by olatechpro** [comment]
> Thanks @olatechpro. Maybe this screenshot helps?
> <img alt="Screen Shot 2020-10-22 at 3 18 43 PM" width="693" src="https://user-images.githubusercontent.com/3868028/96919565-f2adb200-1479-11eb-8ac7-3c364ba11ce1.png">

Yes, i got it now

**Comment by olatechpro** [comment]
I got it wrong initially because i didn't notice this is a seperate issue. I thought it was linked to #16 as i followed email notification and fail to check title

**Comment by stevejburge** [comment]
No worries. This is one task that we will approach soon.
