### ISSUE TITLE
CME Cap read message

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#855]
I saw this broken error message from a user screenshot
<img width="1123" alt="Screenshot 2023-07-22 at 7 47 43 AM" src="https://github.com/publishpress/PublishPress-Capabilities/assets/3868028/7e2ae44c-551a-41ad-8f2d-17b094b9a791">

**Comment by olatechpro** [comment]
@stevejburge I see you added this issue 2 days ago but when i checked, it shouldn't be happening. Can you confirm if it's from an old issue?

**Comment by stevejburge** [comment]
@olatechpro This was a support ticket from yesterday. Perhaps he's running an old version of the plugin. I'll follow up with him
