### ISSUE TITLE
Add demo content for Frontend Features and Admin Feature

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#871]
I wonder if we can add some demo examples for Pro users in Frontend Features, Editor Features, Admin Features etc.

They would be disabled by default

**Comment by olatechpro** [comment]
@stevejburge 
1. Is this only for first time install and not including existing users
2. You mentioned Pro users. So, this demo content is for Pro version only?

**Comment by stevejburge** [comment]
@olatechpro Yes and yes

I wonder if we can come up with some good examples for Pro users. This feature is a little unique and having examples may help people to use them.

**Comment by stevejburge** [comment]
@olatechpro I think those are really excellent ideas. Let's add those and use them as a great starting point
