### ISSUE TITLE
Manage tags capability requires manage categories capability

### ISSUE THREAD

**Issue by samhermes** [publishpress/PublishPress-Capabilities#872]
## Expected Behavior

In Term Taxonomies Capabilities, a role could be limited to manage tags and not categories. In this scenario, they would only see the tags menu item under the posts menu, and not the categories menu item.

## Current Behavior

Currently, when a user has a capability to manage tags but not categories, both the tags and category pages are inaccessible to them.

## Steps to Reproduce (for bugs)

1. Go to the Capabilities page in the admin: `/admin.php?page=pp-capabilities`.
2. Switch to the Editor role, and open the Taxonomies tab.
3. Uncheck the "Manage" box next to categories, and check the "Manage" box next to tags.
4. Sign in as an editor, and see that `/edit-tags.php?taxonomy=post_tag` and `/edit-tags.php?taxonomy=category` are both inaccessible.

## Your Environment

* Version used: 2.8.1
* WordPress version: 6.2.2

**Comment by stevejburge** [comment]
Thanks @samhermes. We'll take a close look at this

**Comment by olatechpro** [comment]
Thanks @samhermes This is WordPress default behaviour when registering Post Tags. We'll be adding a tooltip to clarify this as mentioned in https://github.com/publishpress/PublishPress-Capabilities/issues/919
