### ISSUE TITLE
Extra checkbox at bottom of list

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#878]
"I noticed that after creating couple of features and adding them into list -there is unnecessary checkbox appears at the bottom of the list."

<img width="935" alt="Screenshot 2023-07-30 at 8 27 13 AM" src="https://github.com/publishpress/PublishPress-Capabilities/assets/3868028/6e462d20-9a4e-4a2e-ba06-eb24ae6c30ea">

**Comment by olatechpro** [comment]
@stevejburge That's Toggle All checkbox same as we have it on other pages. The only difference is the Toggle All text removed per your request in https://github.com/publishpress/PublishPress-Capabilities/issues/868

So, are you asking for the toggle all to be removed completely on the screen just incase I misunderstood the initial issue as I only removed the text?

**Comment by stevejburge** [comment]
@olatechpro Not quite - it looks like there are 2 "Toggle All" checkboxes?
<img width="194" alt="Screenshot 2023-07-31 at 7 23 08 AM" src="https://github.com/publishpress/PublishPress-Capabilities/assets/3868028/9645deed-caa5-47b3-bc04-939aad023801">

**Comment by olatechpro** [comment]
![toggle-all](https://github.com/publishpress/PublishPress-Capabilities/assets/46832636/cf990db4-4230-46d0-b4ce-ea8d9eb001fe)
Isn't that how was have it on other pages? One at the top and one at the bottom? Here's Nav menu screenshot for example @stevejburge

**Comment by stevejburge** [comment]
Thanks. @olatechpro Sure, but this is what we see after adding a new entry:

<img width="635" alt="Screenshot 2023-07-31 at 7 30 17 AM" src="https://github.com/publishpress/PublishPress-Capabilities/assets/3868028/cd7ac219-9c3e-47e8-b3a4-a1217d6e4c88">

**Comment by olatechpro** [comment]
Okay

**Comment by olatechpro** [comment]
Sorry, I realised I didn't notice the second one and missed the part that it only happens when need items are added

**Comment by olatechpro** [comment]
Fixed
