### ISSUE TITLE
Block access to admin menu links

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#9]
A ton of people want to be able to block access to specific plugins (ideally by hiding the menu links)

Some plugins allow you to customize the menu links in many ways. We can just add a permissions layer

**Comment by stevejburge** [comment]
The closest example is the "Menu Options" feature in the Adminimize plugin https://wordpress.org/plugins/adminimize/

You can see the settings here: /wp-admin/options-general.php?page=adminimize-options#config_menu

<img width="1085" alt="Screen Shot 2020-09-23 at 11 50 49 AM" src="https://user-images.githubusercontent.com/3868028/94037146-0ee30400-fd93-11ea-9ffe-db392f8e0773.png">

**Comment by agapetry** [comment]
@stevejburge  There is some risk here that by bundling this into a Capabilities plugin, users get the impression that hiding the plugin menu equals blocking access to all that plugin's functions.  It doesn't.  Hiding a plugin's menu is just that: a way to make access less convenient or partially broken.  Even if it's implemented with a hard blockage of the plugin page at the PHP level, there will still potentially be operations which a plugin's custom capabilities allow to be performed by direct URL.

**Comment by stevejburge** [comment]
@agapetry Agreed. We'll need to make that clear on the screen and the documentation

**Comment by agapetry** [comment]
This feature was developed by @olatechpro :
https://github.com/publishpress/PublishPress-Capabilities/pull/72

... with adaptations and a few fixes by @agapetry 

The following commits were to transfer the code from free to Pro, along with some refactoring:

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/4f322e6cb0992dbea42656b50da3327b4ba86618

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/354aa6461c13586cb17152d7e0767701f96c1641

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/32ce3e8081ccc9d20c1892822e4b878327d5c83d

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/abb9874772409e13b50098bce6b2966d14de12d8

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/19ceb4ff80093a471248cd30135e2bd0b9440aac

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/060723e0a57423761f05b007aeab43cd3e85ce80

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/e8487c761effe1d16592e39fbf2aa72822296564

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/5b0ac7df1fac6b3cc8a94a4f4b30d64be21532a4

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/469d5d3bfe61fc6990bc4dd26ef2bdb19a0fe34d


Additional changes by @agapetry :

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/dbb6b545700336298dabf89081ee64e5dc7ac7ef

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/a4414f75cffd02b70af65f2c1a8f121b0f335bd0

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/f515b037d1c6ea2c298e46ffe9813fee65a3ccfe

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/4329a6b5a028abc06ea095ce85f80e63daa1965f
