### ISSUE TITLE
Match sidebar design

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#930]
Can we update the design of the second sidebar box to match the first?

<img width="408" alt="Screenshot 2023-10-20 at 10 36 00 AM" src="https://github.com/publishpress/PublishPress-Capabilities/assets/3868028/faa9408d-6a1d-4581-af4d-24ede9aa6397">

**Comment by olatechpro** [comment]
![st](https://github.com/publishpress/PublishPress-Capabilities/assets/46832636/1fdb08d5-3fa5-4bfd-b171-8ccd29f7080f)

@stevejburge Here's how it looked on my end, what browser is that?

**Comment by stevejburge** [comment]
@olatechpro This is in Safari
