### ISSUE TITLE
Admin area: Block by URL

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#97]
This would be a useful feature for some plugin settings that don't have a menu link.

For example:

> Is it possible to give a user access to a specific page within the Admin section for read only? I use WPForms. They have a section that shows the forms submitted by form name. I want to give specific user roll ability to (preferrably) read only access to only the details for one form. The page name is wp-admin/admin.php?page=wpforms-entries&view=list&form_id=1265.

**Comment by stevejburge** [comment]
@olatechpro yes, please. This can be in the Pro area of the "Admin Features" screen

**Comment by olatechpro** [comment]
This is a PRO PR https://github.com/publishpress/PublishPress-Capabilities-Pro/pull/74
