### ISSUE TITLE
Extra items in the "Admin Menus" beta

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#98]
Some text items ... 

Links should not be there:
<img width="321" alt="Screen Shot 2021-01-28 at 1 09 32 PM" src="https://user-images.githubusercontent.com/3868028/106180410-3d6e5280-616a-11eb-885f-20163eeb196e.png">

Background appears twice:
<img width="293" alt="Screen Shot 2021-01-28 at 1 11 04 PM" src="https://user-images.githubusercontent.com/3868028/106180461-4eb75f00-616a-11eb-9655-d8d4d1cde40f.png">

Authors and Checklists both appear twice:
<img width="287" alt="Screen Shot 2021-01-28 at 1 20 43 PM" src="https://user-images.githubusercontent.com/3868028/106181485-a4d8d200-616b-11eb-822c-ea91eaeba0fc.png">

**Comment by olatechpro** [comment]
Thought we fixed that in this PR https://github.com/publishpress/PublishPress-Capabilities/pull/83?

Maybe it's yet to be added to Pro version

**Comment by stevejburge** [comment]
Awesome, thanks @olatechpro

**Comment by agapetry** [comment]
Okay, I merged those fixes back in.
