### ISSUE TITLE
Ordering of items in the "Admin Menus" beta

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#99]
Sorry for the bad image. It looks like the ordering of menu items is a little haphazard.

Core items are loaded first and then plugins in a jumbled order:
![order](https://user-images.githubusercontent.com/3868028/106181320-76f38d80-616b-11eb-8ff1-bacb061495f3.jpg)

**Comment by stevejburge** [comment]
Ordering of the default menus is a bit odd too:
<img width="500" alt="Screen Shot 2021-01-28 at 1 36 07 PM" src="https://user-images.githubusercontent.com/3868028/106183210-f2563e80-616d-11eb-9e2a-9dbadcba5e7e.png">

**Comment by agapetry** [comment]
Fixed by running $admin_global_menu through ksort()
